### ISSUE TITLE
Not able to access cloudinary & alamofire libraries after installing pod in my objective c project

### ISSUE THREAD

**Issue by vinayakpal** [cloudinary/cloudinary_ios#102]
Hi,
I need to upload a picture on cloudinary to get back a response in my iOS application which is based on Objective-C platform. After i successfully added pods file, xcode ask me to update current swift syntax. when i convert it severals of error has displayed into my project. Secondly, when i added it through git repo it couldn't shows any supported protocol command and method. please help me this out as i couldn't find any path to import cloudinary in my objective c project

**Comment by shirlymanor** [comment]
Hey,
You can find Cloudinary's Objective-C library on tag 1.0.15. The tests provided can give you some sense of how to use our API. For example - 
https://github.com/cloudinary/cloudinary_ios/blob/1.0.15/CloudinaryTests/UploaderTests.m#L90

Please note that you can also use our latest SWIFT library (https://github.com/cloudinary/cloudinary_ios) within an Objective-C project by setting up a bridging mechanism.
