### ISSUE TITLE
No Such Module Crypto

### ISSUE THREAD

**Issue by MandeepSingh1** [cloudinary/cloudinary_ios#103]
![screen shot 2017-09-13 at 4 56 52 pm](https://user-images.githubusercontent.com/11526089/30375033-b4d81212-98a4-11e7-8896-1740a9cda11c.png)

![screen shot 2017-09-13 at 4 07 58 pm](https://user-images.githubusercontent.com/11526089/30373090-c61ecb26-989d-11e7-96c3-77156dd8b22c.png)

Worst SDk i ever use, Worst Support System of SDK, i am using the Cloudinary SDK, everytime am try to run the code this 2 errors come, i have remove the pod file , remove my workspace , remove pods. Then start it from the new still overtime am getting this error. Even i contact the cloudinary, still they are not providing me the proper solution. Now am stuck in the end of my project. Everything is working fine, except Cloudinary. If someone can help me please i need to get out from this issue.

Pod file :-  pod 'Cloudinary', '~> 2.0'

**Comment by AndrewZhatkin** [comment]
@MandeepSingh1 Rename your "Xcode 8.3.1.app" to "Xcode.app" or update path for CommonCrypto.h in "/Pods/Cloudinary/Cloudinary/Frameworks/CLDCrypto/iphoneos/CLDCrypto.framework/module.map". It helps me.

**Comment by MandeepSingh1** [comment]
@AndrewZhatkin hello thanx for your answer, but in this there is no CommonCrypto.h file in Cloudinary. Where is that file can you tell me. Because am trying to resolve this error from last 2 weeks

**Comment by AndrewZhatkin** [comment]
@MandeepSingh1 Path to CommonCrypto.h is used in "**{YOUR_PROJECT_PATH}**/Pods/Cloudinary/Cloudinary/Frameworks/CLDCrypto/iphoneos**(OR iphonesimulator)**/CLDCrypto.framework/module.map"

**Comment by MandeepSingh1** [comment]
am not getting your point , here is the code can you tell me how to do it
module CLDCrypto [system] {
  header "/Users/osvinuser/Desktop/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk/usr/include/CommonCrypto/CommonCrypto.h"
  header "/Users/osvinuser/Desktop/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk/usr/include/CommonCrypto/CommonRandom.h"
  export *
}

**Comment by AndrewZhatkin** [comment]
@MandeepSingh1 Change ".../Xcode.app/..." to ".../Xcode 8.3.1.app/..."

**Comment by MandeepSingh1** [comment]
Still am getting the same error

**Comment by MandeepSingh1** [comment]
Actually i uploaded the wrong image, i updated my question @AndrewZhatkin

**Comment by AndrewZhatkin** [comment]
@MandeepSingh1 I think you need to review this discussion https://github.com/cloudinary/cloudinary_ios/issues/75

**Comment by MandeepSingh1** [comment]
I even try this also, now my Xcode position is /Applications/Xcode.app/Contents/Developer still am getting error

**Comment by AndrewZhatkin** [comment]
Now try to remove Cloudinary from Podfile and install again.

**Comment by kylehorn** [comment]
I'm getting the same issue on Xcode 9. This has been an issue for a while now.

**Comment by MandeepSingh1** [comment]
@kylehorn, can you show me what's your issue my issue has been resolved few minutes ago. May be I can help you 

@Andrew thank you so much for your help, you helped me lot thanks for your precious time

**Comment by kylehorn** [comment]
@MandeepSingh1 It's the same issue you reported above in the module map file. I've tried removing and reinstalling cloudinary in the podfile with no luck.

**Comment by kylehorn** [comment]
@MandeepSingh1 I fixed it. Updated the path for Xcode
