### ISSUE TITLE
Unable to compile on Xcode 9 with iOS11 simulator

### ISSUE THREAD

**Issue by Shivam101** [cloudinary/cloudinary_ios#107]
Hello,

I am trying to compile on Xcode9(final release) with the target simulator as iOS11, but I keep getting the missing `CLDCrypto` error. None of the solutions posted in the other issues worked for me. 
What did work was making the following change change in the `module.map`  file in the `CLDCrypto.framework` - 
  `"/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk/usr/include/CommonCrypto/CommonCrypto.h"`
**to** 
`"/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/CommonCrypto/CommonCrypto.h"`

I had to make the same change in the `iphoneos` folder as well to run it on my device. While this works, I feel it's not the ideal solution and I wouldn't ideally want to make any change in the library's source itself. 

Any reason we have a version(10.3) set here? Instead of just `iPhoneSimulator.sdk` ? Any other solution to fix this issue? 

Thanks!

**Comment by H2CO3** [comment]
This. I am experiencing the same issue.

**Comment by dionc** [comment]
I'm getting this too. It's causing local builds to fail, as well as builds on CircleCI.

**Comment by roeeba** [comment]
Hi, our dev team are reviewing this. We will update as soon as there're any insights.

**Comment by Sethmr** [comment]
This is last pod needing Xcode 9/Swift 4 updates before we update our project.

**Comment by roeeba** [comment]
Hey, guys. To resolve this issue please delete the 'Pods' folder in your project root and re-run `pod install`. This will force the module map creation script to re-run and create the right header files.

**Comment by H2CO3** [comment]
@roeeba Thanks!

**Comment by Sethmr** [comment]
"pod deintegrate" is the command I normally use to remove pods in case anyone needed it.

**Comment by Shivam101** [comment]
@roeeba This should also work if I carry out the following steps - 
1. Remove `cloudinary` from pod file
2. Run Pod install
3. Add `cloudinary` back to pod file
4. Run pod install to reinstall the cloudinary pod.

Is that correct?

**Comment by luispiura89** [comment]
Hello there

Did pod deintegrate and pod install steps fixed this issue for someone?

**Comment by Shivam101** [comment]
@luispiura89 Yes, these steps fixed the issue for me.

**Comment by luispiura89** [comment]
I did the same but the Cloudinary is not getting the correct header. It still getting the 10.3 sdk reference for simulator and for device.

`module CLDCrypto [system] {
  header "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk/usr/include/CommonCrypto/CommonCrypto.h"
  header "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk/usr/include/CommonCrypto/CommonRandom.h"
  export *
}`

**Comment by tditchek** [comment]
@luispiura89 removing the version number from the module worked for me. it should look like this:

`module CLDCrypto [system] { header "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/CommonCrypto/CommonCrypto.h" header "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/CommonCrypto/CommonRandom.h" export * }`

**Comment by luispiura89** [comment]
@tditchek thanks ! I actually was not clearing the previous pods correctly. I found this set of command to clean the pods an reinstall them again.

`rm -rf ~/Library/Caches/CocoaPods; rm -rf Pods; rm -rf ~/Library/Developer/Xcode/DerivedData/*; pod deintegrate; pod setup; pod install;`

**Comment by roeeba** [comment]
Hey, guys. I see that you all found a workaround for this. We're working to find a more permanent solution. We'll update here on any progress in this direction.

**Comment by Sethmr** [comment]
The first is that Right now if you are using Swift 4, you need to do this:

pod 'Cloudinary', '~> 2.0.2'

And then add this before the last end statement somewhere in the taret 'YourAppName' do:

post_install do |installer|
installer.pods_project.targets.each do |target|
if target.name == 'Cloudinary'
target.build_configurations.each do |config|
config.build_settings['SWIFT_VERSION'] = '3.2'
end
end
end
end

I still would like to get a Swift 4 update, but this works for now with only a couple warnings.

**Comment by hanandev** [comment]
Cloudinary is the most core library we used in our app so Please update the new release for swift 4 we will wait for some good news thanks in advance

**Comment by roeeba** [comment]
Hey Guys. Last week we've published a Release Candidate for our iOS library - 2.0.4-rc1. This RC includes support for Swift 4 and the removal of CLDCryptoModule.
Could you please install it and let us know if you see any issues?

**Comment by pavan309** [comment]
Any update on when 2.0.4 will be released?

**Comment by shirlymanor** [comment]
@pavan309 We published the new version. Can you please try and let us know if that works for you?

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Comment by dipeshrajputh** [comment]
> @luispiura89 removing the iOS version number from the module worked for me. it should look like this:
> 
> `module CLDCrypto [system] { header "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/CommonCrypto/CommonCrypto.h" header "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/CommonCrypto/CommonRandom.h" export * }`

Just Remove version  ofter that step its working thanks .
