### ISSUE TITLE
CLDConfiguration' is unavailable: cannot find Swift declaration for this class

### ISSUE THREAD

**Issue by j4nos** [cloudinary/cloudinary_ios#109]
Can not build with Frameworks. Imported both Framework. What is the problem?

<img width="1438" alt="kepernyofoto 2017-10-01 - 23 27 01" src="https://user-images.githubusercontent.com/11924475/31059173-42f80b2e-a700-11e7-8798-65197055dca5.png">

**Comment by roeeba** [comment]
Hi, @j4nos. Once your other thread (https://github.com/cloudinary/cloudinary_ios/issues/110) is resolved, this should be resolved along with it. If you'll still have issues, please let us know.

**Comment by roeeba** [comment]
Hi @j4nos. We've just published a Release Candidate for our iOS library - `2.0.4-rc1`. This RC includes support for Swift 4 and the removal of CLDCryptoModule.
Could you please install it and let us know if you still see the issue?

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
