### ISSUE TITLE
Crashes while uploading image

### ISSUE THREAD

**Issue by Ramshandilya** [cloudinary/cloudinary_ios#11]
CLUploader* uploader = [[CLUploader alloc] init:self.cloudinary delegate:self];
[uploader upload:self.profileImage options:@{}];
![screen shot 2014-08-08 at 3 04 57 pm](https://cloud.githubusercontent.com/assets/2031908/3855007/4e71f1c4-1edf-11e4-9837-e2d23e9579ea.png)

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.
