### ISSUE TITLE
Invalid Signature - GenerateCLDCryptoModule

### ISSUE THREAD

**Issue by noumantahir** [cloudinary/cloudinary_ios#120]
I am using manual Cloudinary integration and is having this error during app store upload...

> ERROR ITMS-90035: "Invalid Signature. Code object is not signed at all. The file at path [BucketListApp.app/Frameworks/Cloudinary.framework/GenerateCLDCryptoModule] is not properly signed

I have tried so many suggestion and workarounds from this repo issues and stackoverflow that I had to finally create this new issue after like 17 hours of attempts.

So far, I have tried many different code signing variants, tried to shift toward pods, downgraded to xcode 8 to add support for swift 2, tried to write code in swift, tried adding a bunch of workaround codes in podFile. But unfortunately I was not able even run Cloudinary SDK using any of the methods above.

The only method worked for me was the manual integration, it works well but only road block now is when I upload to app store from XCode I get this error.

I am willing to try anything really, even though I am just exhausted, any kind of assistance will be awesome. Thanks

![screen shot 2017-12-04 at 5 12 24 pm](https://user-images.githubusercontent.com/6298342/33552351-79b3c7a0-d916-11e7-9c05-f62e03158ad5.png)

**Comment by shirlymanor** [comment]
We are working on a new ios version that will fix this issue.
Please stay tuned :)

**Comment by roeeba** [comment]
We've just published a Release Candidate for our iOS library - `2.0.4-rc1`. This RC includes support for Swift 4 and the removal of CLDCryptoModule.
Could you please install it and let us know if you still see any issues?

**Comment by noumantahir** [comment]
will be the first I am gonna try as I start work tomorrow. thanks.

**Comment by noumantahir** [comment]
Attempt Result:
before I was using 2.0.3. updated to 2.0.4-rc1 using `git pull` inside `cloudinary_ios`, now it's giving me these errors during build...
![screen shot 2017-12-08 at 10 50 30 pm](https://user-images.githubusercontent.com/6298342/33778442-6e44c43a-dc6a-11e7-8142-2202502448e4.png)

**Comment by roeeba** [comment]
Hi @noumantahir. Please verify that you are compiling the Cloudinary target using Swift 4. If you already do, please elaborate on how are you using Cloudinary (cocopods, manual install, etc). Thanks

**Comment by noumantahir** [comment]
@roeeba I am not using pods, they never worked for me in the first place even with workarounds added.

I am using manual integration as mentioned here...https://github.com/cloudinary/cloudinary_ios#working-with-the-cloudinary-ios-sdk-manually

Using this method, my project compiles for `2.0.3` and does not for both `2.0.4` and `2.0.4-rc1`

let me know if you need more info, always excited to assist.

**Comment by roeeba** [comment]
Hi @noumantahir. Best practice would be installing the package using pods, now that the swift versions are updated. In addition, it looks like you're working with objective C, is that right? is there a reason you're not using swift? can you please try and open a new project in Swift and import our package using pods? let us know if it works for you then?

**Comment by noumantahir** [comment]
Hey, sorry for belated reply...

I am using `ReactNative` as my primary platform of development, using `cloudinary` init via something called `NativeModule` and `Objective-C` was the only directly supported language for that, there is support for swift though but I found it quite complicated to implement as I come from a different programming background. I can try to replicate and test things out though...

will get back to you guys.

**Comment by noumantahir** [comment]
Attempt:
Dropped manual linkage of libraries and moved to pod...tried out  `pod 'Cloudinary', '2.0.4-rc1'`. Got this error on cleaning project, it's related to swift support for Alamofire...
![screen shot 2017-12-19 at 7 14 03 am](https://user-images.githubusercontent.com/6298342/34137383-7e5d0678-e48c-11e7-859a-42b8acc7eefe.png)

**Comment by noumantahir** [comment]
Resolved the issue by removing GenerateCLDCryptoModule file from relevant directory. It may not be called a solution but migrating to swift was not a viable solution for me because of ReactNative, it was way more work. using 2.0.3

At Least it's not a roadblock in my development for now. Thanks

**Comment by noumantahir** [comment]
Resolved the issue by removing GenerateCLDCryptoModule file from relevant directory. It may not be called a solution but migrating to swift was not a viable solution for me because of ReactNative, it was way more work. using 2.0.3

At Least it's not a roadblock in my development for now. Thanks
