### ISSUE TITLE
2.0.4-rc1 Alamofire requirement 4.5.1

### ISSUE THREAD

**Issue by Sethmr** [cloudinary/cloudinary_ios#122]
I am currently using Alamofire 4.6.0, and being constrained to use 4.5.1 by Cloudinary. I personally think that Alamofire shouldn't be a dependency of Cloudinary, but if it has to be, please configure the cocoapods dependencies accordingly to prevent this issue.

4.6.0 of Alamofire doesn't directly give me anything I want, but I am looking forward to one of their updates in a release or two and don't want to be constrained by cloudinary. Outside of this issue, 2.0.4-rc1 seems to be working fine. I'll have it thoroughly tested over the next week.

**Comment by roeeba** [comment]
Hi @Sethmr. Thanks for pointing it out. We'll do our best to constantly deploy versions and keep the Alamofire dependency updated.

**Comment by Sethmr** [comment]
I appreciate that.

**Comment by roeeba** [comment]
Hi @Sethmr, Just letting you know that our latest release uses Alamo release 4.6.0. 

I will close the ticket now, but please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
