### ISSUE TITLE
Can't upload to Cloudinary in Swift 4

### ISSUE THREAD

**Issue by sikfreeze** [cloudinary/cloudinary_ios#123]
Hi, 
I've tried both, the version 2.0.2 and 2.0.4-rc1 with Swift 4 in XCode 9.1. However, when I tried to upload the image to Cloudinary, there were just no responses back to the complete handler, not even an error. I've also ran the sample project, I can select and save image but the images are just not uploaded to Cloudinary. 

Below are my codes, has anyone encountered a similar problem? Thank you:

let config = CLDConfiguration(cloudName: "MY_CLOUD_NAME", apiKey: "MY_API_KEY")
let cloudinary = CLDCloudinary(configuration: config!)
        
        cloudinary.createUploader().upload(data: self.imageData!, uploadPreset: "test_preset_name", params: nil, progress: { (progress) in

        }) { (response, error) in
            print(response?.url)
        }

**Comment by roeeba** [comment]
Hi @sikfreeze. Could you please share you cloud-name, so we can check your logs?

**Comment by sikfreeze** [comment]
Hi @roeeba , my cloud-name is dbeubc247

Now, I just tried using the simulator instead of the actual device, iPhone 5, I was using earlier. In the simulator, strangely, I received upload progress and response to the complete handler, even though, the response is always an error with the code 400

"error	NSError?	domain: "com.cloudinary.error" - code: 400	0x000060000084d380"

I already set the preset name to use with unsigned upload but it keeps getting the same result

Thank you for your help and the fast response

**Comment by roeeba** [comment]
Thanks. Could you please also let us know the value populating `self.imageData`?

**Comment by sikfreeze** [comment]
@roeeba  It came from this line

self.imageData = UIImageJPEGRepresentation(image!, 0.8) as Data?

**Comment by roeeba** [comment]
Thanks @sikfreeze. Could you please mention the exact `file` value sent to Cloudinary in the request? we suspect the error is related. Thanks!

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
