### ISSUE TITLE
Issue when both FirebasePerformance and Cloudinary SDK in one Project

### ISSUE THREAD

**Issue by kuyazee** [cloudinary/cloudinary_ios#124]
Cloudinary seems to not be able to upload files when FirebasePerformance is added in One Project

This seems to be because FirebasePerformance is doing method Swizzling but I'm not sure which ones cause this bug.

Setup Used:
IDE: Xcode Version 8.3.2 (8E2002)
Swift Version: 3.0
Cloudinary Installation Method: Via Cocoapods

**Comment by yakirp** [comment]
Hi @kuyazee ,

We are sorry for the late response here.

Could you please elaborate more on what exactly did not work for you?  We need this information in order to reproduce this on our end. 

Thanks,
Yakir

**Comment by kuyazee** [comment]
Hi @yakirp,

Thank you for the response.

After further investigation on my part, it seems that I was just mistaken. It was a mistake on my part. Sorry for not updating this ticket.

Thanks,
Zonily
