### ISSUE TITLE
Can't use Cloudinary with Eureka pod

### ISSUE THREAD

**Issue by pershanti** [cloudinary/cloudinary_ios#125]
I'm using XCode v 9.2, and Swift 4. I installed the Cloudinary pod 4.02 . When I import it 
("Import Cloudinary") into a Swift file already using Eureka ( https://github.com/xmartlabs/Eureka) the Eureka framework stops working, and none of their classes are usable. My other pods seem to be 100% functional. I've attached my viewcontroller as a text file, and the dependencies are listed there. I also attached my podfile as a txt file. Is this possibly a Swift version problem?

[Podfile.txt](https://github.com/cloudinary/cloudinary_ios/files/1586259/Podfile.txt)
[OnboardingViewController.txt](https://github.com/cloudinary/cloudinary_ios/files/1586257/OnboardingViewController.txt)
 

Best,
Shantini Vyas

**Comment by yakirp** [comment]
Hi @pershanti ,

There is a custom operator conflict between our SDK and yours. 
We will fix this issue in our next release.

Thanks for notifying us about that.

Best, 
Yakir

**Comment by yakirp** [comment]
Hi @pershanti , 
Our latest iOS SDK includes a fix for this issue, so I'm closing this thread.

Best,
Yakir
