### ISSUE TITLE
setStreamingProfile unavalaible

### ISSUE THREAD

**Issue by losetchi** [cloudinary/cloudinary_ios#130]
I am trying to integrate cloudinary in my app to stream videos but unfortunatelly cannot do that due to the following error: Value of type 'CLDTransformation' has no member 'setStreamingProfile'.

The generated swift code from cloudinary console:
cloudinary.createUrl().setResourceType("video").setTransformation(CLDTransformation().setStreamingProfile("full_hd")).generate("jellyfish.mp4"))

Pod version: 2.1.0

**Comment by shirlymanor** [comment]
@losetchi currently we are not supporting setStramingProfile. It is on our roadmap but no ETA yet.
Alternatively, you can use `setParam("sp", value: "full_hd")`.

**Comment by shirlymanor** [comment]
Just wanted to add that we are now supporting it also by using `setStreamingProfile`.
For example:

CLDEagerTransformation().setFormat("m3u8").setStreamingProfile("full_hd")
