### ISSUE TITLE
Latest pod version does not have swift 4 support

### ISSUE THREAD

**Issue by paultnp** [cloudinary/cloudinary_ios#134]
Hello,

I am not able to use cloudinary in my swift 4 project. I am using below in pod file

    pod 'Cloudinary', '~> 2.0'

Which installs Cloudinary (2.0.3), and gives error on compile. Can you suggest how can I use the library in Swift 4 project.

**Comment by shirlymanor** [comment]
@paultnp Can you please try using:

```
pod 'Cloudinary'
```

**Comment by paultnp** [comment]
@shirlymanor Thanks is worked
