### ISSUE TITLE
undeclared fixedWidth error

### ISSUE THREAD

**Issue by dheerajPaul** [cloudinary/cloudinary_ios#135]
i have tried Cloudinary through cocoapods on Xcode 8.3 and swift 3. when I built it throws an error saying 'undeclared fixedWidth'

**Comment by shirlymanor** [comment]
We release a new version of our SDK. Can you please try it again with the new version?

**Comment by shirlymanor** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
