### ISSUE TITLE
Can't use in ObjC 

### ISSUE THREAD

**Issue by SandeepAggarwal** [cloudinary/cloudinary_ios#138]
I am getting following compilation errors for objC project:
`No visible @interface for 'CLDConfiguration' declares the selector 'initWithCloudinaryUrl:'`

`No visible @interface for 'CLDCloudinary' declares the selector 'initWithConfiguration:networkAdapter:sessionConfiguration:'`

`No visible @interface for 'CLDCloudinary' declares the selector 'createUploader'`

`No visible @interface for 'CLDUploader' declares the selector 'uploadWithData:uploadPreset:params:progress:completionHandler:'`

`Property 'secureUrl' not found on object of type 'CLDUploadResult *'`

`No visible @interface for 'CLDUploadRequest' declares the selector 'response:'`

`No visible @interface for 'CLDUploadRequest' declares the selector 'cancel'`

I am using the Cloudinary version 2.2.1 via Cocoapods

**Comment by shirlymanor** [comment]
Here is a sample project using objective C:
https://github.com/cloudinary/cloudinary_ios/tree/1.0.15
If you have any issue, you're more than welcomed to [open a ticket](http://support.cloudinary.com/tickets/new) with your code and we will take a look at it.

**Comment by gil-wisdo** [comment]
I'm having the same issue. Seems like this library isn't compatible with Swift 4.0 @ObjC 
See also:
https://stackoverflow.com/questions/45656671/unable-to-access-swift-class-from-objective-c-property-not-found-on-object-of

**Comment by shirlymanor** [comment]
@gil-wisdo we are working on it. I'll update when we'll have any insights. stay tuned :)

**Comment by shirlymanor** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
