### ISSUE TITLE
CLUploader crash sometimes.

### ISSUE THREAD

**Issue by oday0311** [cloudinary/cloudinary_ios#14]
I am using crashlytics sdk to track the crash in ios , and found serveral crash cases relate with CL sdk.
can you give some support on this?

Pinnacle	
CLUploader.m line 625
-[CLUploader connection:didSendBodyData:totalBytesWritten:totalBytesExpectedToWrite:]

Thread : Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x30de3f46 objc_msgSend + 5
1  Pinnacle                       0x00198b59 -[CLUploader connection:didSendBodyData:totalBytesWritten:totalBytesExpectedToWrite:] (CLUploader.m:625)
2  CFNetwork                      0x23125d43 ___ZL31_NSURLConnectionDidSendBodyDataP16_CFURLConnectionlllPKv_block_invoke + 38
3  CFNetwork                      0x23136f81 __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke + 56
4  CFNetwork                      0x23136f3b -[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:] + 182
5  CFNetwork                      0x2313702d -[NSURLConnectionInternal _withActiveConnectionAndDelegate:] + 36
6  CFNetwork                      0x23124e47 _NSURLConnectionDidSendBodyData(_CFURLConnection*, long, long, long, void const*) + 90
7  CFNetwork                      0x230ea797 ___ZN27URLConnectionClient_Classic25_delegate_didSendBodyDataE18UploadProgressInfo_block_invoke + 82
8  CFNetwork                      0x230e8889 ___ZN27URLConnectionClient_Classic18_withDelegateAsyncEPKcU13block_pointerFvP16_CFURLConnectionPK33CFURLConnectionClientCurrent_VMaxE_block_invoke_2 + 60
9  CFNetwork                      0x2303cf4d RunloopBlockContext::_invoke_block(void const*, void*) + 60
10 CoreFoundation                 0x234eee2d CFArrayApplyFunction + 36
11 CFNetwork                      0x2303ce07 RunloopBlockContext::perform() + 182
12 CFNetwork                      0x2303cccd MultiplexerSource::perform() + 216
13 CFNetwork                      0x2303cb61 MultiplexerSource::_perform(void*) + 48
14 CoreFoundation                 0x235a3d57 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 14
15 CoreFoundation                 0x235a3167 __CFRunLoopDoSources0 + 218
16 CoreFoundation                 0x235a17cd __CFRunLoopRun + 772
17 CoreFoundation                 0x234ef3c1 CFRunLoopRunSpecific + 476
18 CoreFoundation                 0x234ef1d3 CFRunLoopRunInMode + 106
19 GraphicsServices               0x2a8ed0a9 GSEventRunModal + 136
20 UIKit                          0x26afd7b1 UIApplicationMain + 1440
21 Pinnacle                       0x0010509b main (main.m:16)

**Comment by GrandSteph** [comment]
Same issue. Did you get any resolution?

**Comment by TalLevAmi** [comment]
According to the stack trace, the error occurs when CLUploader is trying to call the progress callback.  Please look into how you are setting up the progress callback.

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.
