### ISSUE TITLE
Add @objc Tags for proper Swift 4.0 to Objective-C Inference

### ISSUE THREAD

**Issue by gil-wisdo** [cloudinary/cloudinary_ios#141]
Hi Again,
Thanks for the reply in #138 
Just to create a new issue so It'll be better organized.

We need proper support for Objective-C projects using this SDK the new Swift 4.0 inference rules.

https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html#//apple_ref/doc/uid/TP40014216-CH10-ID122

Thanks again 🥇

**Comment by yakirp** [comment]
Hi @gil-wisdo ,
I'm sorry for the late response. this issue has been fixed a long time ago.

Please let me know if it works for you

Cheers,
Yakir

**Comment by yakirp** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
