### ISSUE TITLE
Need to use updated alamofire

### ISSUE THREAD

**Issue by nigelbro** [cloudinary/cloudinary_ios#145]
Your pod is using an outdated version of alamofire. I should not have to downgrade to 4.5.1 just to use it please fix

**Comment by shirlymanor** [comment]
@nigelbro sorry for the late response, currently, we're using 4.6.0 (which was released in December). We will use the next version (4.7.0) on our next version (in a month).

**Comment by roeeba** [comment]
Alamofire version was updated. Closing.
