### ISSUE TITLE
Cloudinary 2.x upload failed in share extension...

### ISSUE THREAD

**Issue by fastma** [cloudinary/cloudinary_ios#146]
I used cloudinary v1.x and uploading is ok with both my app and share extension. When I upgrade to 2.x, I got the connection failes with -995 when made from a share extension.
Then, I made configuration sharedContainerIdentifier below: 

```
let config = CLDConfiguration(cloudName: CLOUDINARY_CLOUD_NAME, apiKey: CLOUDINARY_PUBLIC_KEY, apiSecret: nil)
let backgroundSessionConfiguration = URLSessionConfiguration.background(withIdentifier: "background.com.myapp.foo")
backgroundSessionConfiguration.sharedContainerIdentifier = DEFAULTS_GROUP_SUITE
let cloudinary = CLDCloudinary(configuration: config, networkAdapter: nil, sessionConfiguration: backgroundSessionConfiguration)
```

but I'm getting intermittent crashes in Alamofire (inside of Cloudinary), and error -999 (request cancelled) now...

Event tried with 
`let config = CLDConfiguration(cloudName: CLOUDINARY_CLOUD_NAME, apiKey: CLOUDINARY_PUBLIC_KEY, apiSecret: nil, secure: true)`
 not working different...

Anyone have a solution for this case?
 @Thanks!

**Comment by bbreier** [comment]
I'm having the same issue

**Comment by fastma** [comment]
Did you solve it @bbreier ?

**Comment by bbreier** [comment]
I did @fastma, I've posted the snippet here: https://github.com/cloudinary/cloudinary_ios/issues/69#issuecomment-386955128

**Comment by roeeba** [comment]
Hi @fastma, we apologize for not responding earlier! Can you please let us know if this issue can be closed or if we can still assist in some way? thanks!

**Comment by fastma** [comment]
Hi @roeeba, Im still stucking at this issue and continuing to investigate more....

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
