### ISSUE TITLE
Upload image with Server signature crash

### ISSUE THREAD

**Issue by stefanocdn** [cloudinary/cloudinary_ios#15]
Hi I am getting this error when trying to upload a picture from IOS:

Invalid Signature 8cd27f15e344fe337f6099afbb09dd2e96f8ecff. String to sign - 'public_id=888f0cf0-0d93-4017-87cc-0356c79d20f8&timestamp=1426595637'

My server side code for generating the signature is:

options = [{height: 800, width: 800, crop: :limit}]
result = Cloudinary::Utils.generate_transformation_string(options)
time = Time.now.to_i
public_id = SecureRandom.uuid
api_key = Cloudinary.config.api_key
signature = Cloudinary::Utils.api_sign_request({public_id: public_id, timestamp: time, transformation: result}, Cloudinary.config.api_secret)
render status: 200, json: {
     signature: signature,
     public_id: public_id,
     timestamp: time,
     api_key: api_key,
     cloud_name: "mycloudname"
   }

My server response is:

{
    "api_key" = mycloudapikey;
    "cloud_name" = mycloudname;
    "public_id" = "888f0cf0-0d93-4017-87cc-0356c79d20f8";
    signature = 8cd27f15e344fe337f6099afbb09dd2e96f8ecff;
    timestamp = 1426595637;
}

I use this dictionary as options for my upload to cloudinary. But I can't add the transformation that matches the one server-side in the options dictionary because:

In the upload method:

- (void)upload:(id)file options:(NSDictionary *)options withCompletion:(CLUploaderCompletion)completionBlock andProgress:(CLUploaderProgress)progressBlock
{
    [self setCompletion:completionBlock andProgress:progressBlock];
    if (options == nil)options = @{};
    NSMutableDictionary *params = (NSMutableDictionary *)[self buildUploadParams:options];
    [self callApi:@"upload" file:file params:params options:options];
}

When the following is called

- (NSDictionary *)buildUploadParams:(NSDictionary *)options

Since I have a signature, the transformation object is not transformed to a string

if (options[@"signature"] == nil) {
        id transformation = [options cl_valueForKey:@"transformation" defaultValue:@""];
        if ([transformation isKindOfClass:[CLTransformation class]]){
            transformation = [((CLTransformation *)transformation)generate];
        }
        [params setValue:transformation forKey:@"transformation"];
        NSArray* tags = [CLCloudinary asArray:options[@"tags"]];
        [params setValue:[tags componentsJoinedByString:@","] forKey:@"tags"];
        NSArray* allowedFormats = [CLCloudinary asArray:options[@"allowed_formats"]];
        [params setValue:[allowedFormats componentsJoinedByString:@","] forKey:@"allowed_formats"];
        [params setValue:[self buildContext:options[@"context"]] forKey:@"context"];
        [params setValue:[self buildFaceCoordinates:options[@"face_coordinates"]] forKey:@"face_coordinates"];
        [params setValue:[self buildEager:options[@"eager"]] forKey:@"eager"];
        [params setValue:[self buildCustomHeaders:options[@"headers"]] forKey:@"headers"];
    } else {
        [params setValue:options[@"transformation"] forKey:@"transformation"];
        [params setValue:options[@"tags"] forKey:@"tags"];
        [params setValue:options[@"allowed_formats"] forKey:@"allowed_formats"];
        [params setValue:options[@"context"] forKey:@"context"];
        [params setValue:options[@"face_coordinates"] forKey:@"face_coordinates"];
        [params setValue:options[@"eager"] forKey:@"eager"];
        [params setValue:options[@"headers"] forKey:@"headers"];
    }

So when this method is called
NSURLRequest *req = [self request:apiUrl params:params file:file];

NSMutableData* postBody = [NSMutableData data];
    for (NSString* param in [params allKeys]){
        NSObject* value = [params valueForKey:param];
        if ([value isKindOfClass:[NSArray class]]) {
            NSArray *arrayValue = (NSArray*) value;
            for (NSString *paramValue in arrayValue) {
                [self encodeParam:postBody param:[param stringByAppendingString:@"[]"] paramValue:paramValue boundary:boundary];
            }
        } else {
            NSString *paramValue = [CLCloudinary asString:value];
            if ([paramValue length] == 0) continue;
            [self encodeParam:postBody param:param paramValue:paramValue boundary:boundary];
        }
    }

NSString *paramValue = [CLCloudinary asString:value];

The asString called on the transformation crashes.

How can I solve that?

**Comment by TalLevAmi** [comment]
Looks like is that server is not returning the transformation parameter in it's JSON.

**Comment by stefanocdn** [comment]
Currently it's "returned" in the signature when calling
    signature = Cloudinary::Utils.api_sign_request({public_id: public_id, timestamp: time, transformation: result}, Cloudinary.config.api_secret)

with the transformation string generated with

    options = [{height: 800, width: 800, crop: :limit}]
    result = Cloudinary::Utils.generate_transformation_string(options)

**Comment by TalLevAmi** [comment]
It also needs to be returned in the JSON and given to the iOS upload method.

**Comment by stefanocdn** [comment]
Thanks very much, it works when doing what you said!
