### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by maurovc** [cloudinary/cloudinary_ios#153]
Hey,

Would it be a problem to add tvOS support to the SDK?

There's an open PR from 2016 with the support added. Do you think it can be done any time soon?

Best regards,

Mauro

**Comment by roeeba** [comment]
Hi @maurovc. I apologize for the very late reply. We're looking into adding more features from the Apple eco-system including tvOS, though this is not currently in our short/middle term plans. We'll update here if and when this will be supported.

**Comment by roeeba** [comment]
As this is currently not on our roadmap, we're closing to this thread. We'll re-open it if and when this will be more relevant. Please let us know if there's anything else we can help with.
