### ISSUE TITLE
Safe request example code

### ISSUE THREAD

**Issue by crspybits** [cloudinary/cloudinary_ios#154]
It seems like the Swift code example here:
https://github.com/cloudinary/cloudinary_ios#safe-mobile-requests
and namely:
```
cloudinary.createUploader().upload(file: fileURL, params: params, completionHandler: { (response, error) in
            // Handle respone
        })
```

should be using the `signedUpload` variant. E.g., 
```
cloudinary.createUploader().signedUpload(file: fileURL, params: params) { result, error in
}
```

**Comment by shirlymanor** [comment]
Thank you for correcting us.
I've forward your feedback to our documentation team to update the doc.

**Comment by shirlymanor** [comment]
@crspybits Thank you for your patience and your feedback. our document is now up to date.
I'm closing this issue. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
