### ISSUE TITLE
Alamofire '~> 4.7' support

### ISSUE THREAD

**Issue by rinat-enikeev** [cloudinary/cloudinary_ios#160]
is it enough to replace 
`s.dependency 'Alamofire', '~> 4.6.0'`
with 
 `s.dependency 'Alamofire', '~> 4.7'`
in pod spec in order to support the latest Alamofire?

**Comment by aditimadan-Cloudinary** [comment]
Hi,

Our latest version uses alamo 4.7.2 now (latest), you can update to our latest version to use it.

Thanks,
Aditi
