### ISSUE TITLE
Issue with test targets and xcodebuild with Cloudinary projects

### ISSUE THREAD

**Issue by crspybits** [cloudinary/cloudinary_ios#163]
I'm using Xcode 9.4 (9F1027a), and Circle CI to run my unit tests. When I added the Cloudinary Cocoapod to my project, I started getting: 

▸ Signing /Users/distiller/Library/Developer/Xcode/DerivedData/roster-hdmfjqymraumdiaibaptjdpikrfm/Build/Products/Debug-iphonesimulator/roster.app/PlugIns/CloudinaryTests.xctest
2018-06-20 12:58:23.004 xcodebuild[670:4014] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
2018-06-20 12:58:23.004 xcodebuild[670:4014] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
2018-06-20 12:58:23.004 xcodebuild[670:4014] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

The build command to run my tests on Circle is:

            xcodebuild \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGN_IDENTITY= \
              PROVISIONING_PROFILE= \
              -sdk iphonesimulator \
              -destination 'platform=iOS Simulator,OS=11.4,name=iPhone 6' \
              -workspace roster.xcworkspace \
              -scheme "dev" \
              clean build test

When I try to run this xcodebuild command on my local system, the same problem arises, but I get some details:

dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire
  Referenced from: /Users/chris/Library/Developer/CoreSimulator/Devices/1583F915-F527-4166-B898-B3F83C5AA889/data/Containers/Bundle/Application/42290892-4C1C-4F60-AA30-2889959AD838/roster.app/roster
  Reason: no suitable image found.  Did find:
	/Users/chris/Library/Developer/CoreSimulator/Devices/1583F915-F527-4166-B898-B3F83C5AA889/data/Containers/Bundle/Application/42290892-4C1C-4F60-AA30-2889959AD838/roster.app/Frameworks/Alamofire.framework/Alamofire: required code signature missing for '/Users/chris/Library/Developer/CoreSimulator/Devices/1583F915-F527-4166-B898-B3F83C5AA889/data/Containers/Bundle/Application/42290892-4C1C-4F60-AA30-2889959AD838/roster.app/Frameworks/Alamofire.framework/Alamofire'

I have been been able reproduce this problem with the attached simplified Xcode project.
[Test.zip](https://github.com/cloudinary/cloudinary_ios/files/2121227/Test.zip)

and the following build command:

            xcodebuild \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGN_IDENTITY= \
              PROVISIONING_PROFILE= \
              -sdk iphonesimulator \
              -destination 'platform=iOS Simulator,OS=11.4,name=iPhone 6' \
              -workspace test.xcworkspace \
              -scheme "Test" \
              clean build test

Any help would be appreciated. Thank you.

Please note that this problem does *not* arise when:
1) Running my tests through the Xcode UI
2) Building, running, or archiving my project

**Comment by shirlymanor** [comment]
@crspybits I tried to delete the version of cloudinary in the pod file and just use `pod 'Cloudinary'`. Then run the pod install and than use the build command. can you try and let me know if that works?

**Comment by crspybits** [comment]
Were you able to reproduce the problem at all with my Test example?

Here's what I did based on your comment:
1) I removed the Pods folder in the Test project
2) I ran pod 'Cloudinary' (with no version specifier)
3) pod install
4) Run the xcodebuild command as above

I see the same failure as I indicated above.

**Comment by shirlymanor** [comment]
@crspybits Yes, I successfully reproduced the error that you got.
The only difference is that I used `pod update` because on CocoaPods 1.0, ` pod update` does not happen on `pod install` by default.
If that still doesn't help, can you please open a support ticket here: support@cloudinary.com for further investigation.

**Comment by crspybits** [comment]
I did a `pod update` and re-ran my build. I found the same issue. I've just sent an email to your support email address. with this issue link. Thanks.

**Comment by shirlymanor** [comment]
Just an update in case anyone has this issue:
It seems like this issue is not related to Cloudinary.
You might want to try to add the following code to the bottom of your Podfile and run pod install

# Workaround for Cocoapods issue #7606

```
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
```
