### ISSUE TITLE
uploading with data works but with url not working in objective c

### ISSUE THREAD

**Issue by redrose2** [cloudinary/cloudinary_ios#167]
Here's what I tried.

NSString *path = @"/var/mobile/Media/PhotoData/Metadata/PhotoData/CPLAssets/group465/1399F277-53B7-40B3-8841-FE2352B56356.JPG";

NSData *data = [NSData dataWithContentsOfFile:path];
[[self.cloudinary createUploader]
 signedUploadWithData:data
 params:params
 progress:^(NSProgress * progress) {}
 completionHandler:^(CLDUploadResult * result, NSError * error) {}//result is not nil, error is nil
];

NSURL *url = [[NSURL alloc] initWithString:path];
[[self.cloudinary createUploader]
 signedUploadWithUrl:url
 params:params
 progress:^(NSProgress * progress) {}
 completionHandler:^(CLDUploadResult * result, NSError * error) {}//result is nil, error is not nil
]; (error.message is "Failed to upload!")

**Comment by shirlymanor** [comment]
You can find Cloudinary's Objective-C library on tag 1.0.15. The tests provided can give you some sense of how to use our API. For example - 
https://github.com/cloudinary/cloudinary_ios/blob/1.0.15/CloudinaryTests/UploaderTests.m#L90

Alternatively, you can use our latest SWIFT library (https://github.com/cloudinary/cloudinary_ios) within an Objective-C project by setting up a bridging mechanism.

**Comment by shirlymanor** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
