### ISSUE TITLE
Swift 4.2 Conversion

### ISSUE THREAD

**Issue by Sethmr** [cloudinary/cloudinary_ios#175]
This is the last SDK to need the update to swift 4.2 out of our 17 pods... this also happened during the Swift 4 update. The developers using your SDK would appreciate the update so we can remove specialized code like below from our podfile and stop getting Xcode warnings.
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == "Cloudinary" then
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
```

**Comment by shirlymanor** [comment]
It's on our road-map but no ETA yet.
I'll update here when I'll have any insights.

**Comment by Sethmr** [comment]
This is complete is the latest version.
