### ISSUE TITLE
CLTransformation on video object not playing video 

### ISSUE THREAD

**Issue by meandkareem** [cloudinary/cloudinary_ios#18]
I'm generating url with 
    NSString *strURL = [NSString stringWithFormat:@"%@.%@",post[@"video"]  [@"public_id"],post[@"video"][@"format"]];
    url = [cloudinary url:strURL options:@{@"transformation": transformation, @"resource_type": @"video"}];

soon as I add some transformations .. like size or format it doesn't load video in player. Url is correct I tested it in Chrome and it works .. 

tnx

**Comment by TalLevAmi** [comment]
Looking at our logs it seems that you are trying to generate mov files. Cloudinary supports outputting videos only in mp4, webm, ogv, and flv formats.

**Comment by meandkareem** [comment]
Yes i added now mp4 format option and now I have another problem . Vidoe is not working on first load . Soon as I push and pop back to controller I can see video . I will try to investigate why video is not loaded first time.

**Comment by taragano** [comment]
I wanted to verify with you whether this issue was resolved. I'll be closing this for now, however if you still encounter with any issues, please feel free to re-open this or contact support@cloudinary.com.

Thanks.
