### ISSUE TITLE
AlamoFire v5 is not supported.

### ISSUE THREAD

**Issue by Sethmr** [cloudinary/cloudinary_ios#181]
The new AlamoFire will be out of beta soon and supports the Codable protocol. This is the one I have been waiting for. If you could please release an update soon after it gets out of beta that would be highly appreciated!!!!!

https://github.com/Alamofire/Alamofire/releases
v5.0.0.beta.1

**Comment by shirlymanor** [comment]
We are always trying to keep up with the new SDK's. I'll update here about supporting the new Alamofire. but no ETA yet.

**Comment by yusuftor** [comment]
Also need to make it work with the latest alamofire -> 4.8.1

**Comment by Sethmr** [comment]
Alamofire version 4.8.2 fixes integration with Xcode 10.2. This should be higher priority than "enhancement" now.

**Comment by nitzanj** [comment]
@Sethmr agreed, supporting swift 5 and Xcode 10.2 (and bumping alamofire to 4.8.2) was prioritised higher than this issue, and released a week ago.
