### ISSUE TITLE
Resource contains a dref (alias) atom

### ISSUE THREAD

**Issue by meandkareem** [cloudinary/cloudinary_ios#19]
I receive this error on every video upload . Same code worked perfectly few days ago .
    
    CLCloudinary *cloudinary = [NANUtility initCloudinary];
    CLUploader* uploader = [[CLUploader alloc] init:cloudinary delegate:self];
    [uploader upload:_videoPath options:@{@"resource_type": @"video"}];

**Comment by TalLevAmi** [comment]
Can you please send a sample of such a file to support@cloudinary.com ?

**Comment by meandkareem** [comment]
sent.

**Comment by TalLevAmi** [comment]
Thanks! 
The issue has been resolved. Please try again.

**Comment by meandkareem** [comment]
Yes it's working . Thanks!
