### ISSUE TITLE
Swift support

### ISSUE THREAD

**Issue by philipheinser** [cloudinary/cloudinary_ios#20]
We try to use this framework in our Swift App and thinks don't go well.

**Comment by nadavofi** [comment]
While it's on our roadmap to build new Swift dedicated client-libraries, today our libraries only offer solution for Objective-C when it comes to native IOS apps.

Having said that, "Cocoa-pods" offers a great solution for setting up bridging between your Swift app and our Objective-C libraries for you.
See the following tutorial: https://www.youtube.com/watch?v=yfkX-p5kW4U

Using the Cloudinary pod (i.e. `pod "Cloudinary"`) will seamlessly set the dependencies for you and allow you working straight with our API from your Swift app.

If you have any specific question on the integration process feel free to open a support ticket and we'll be happy to assist further.

**Comment by grantkemp** [comment]
+1 for cocoapods.

**Comment by neelamsharma12** [comment]
Integrating Cloudinary in swift using cocoapods

Steps:
1. First, Create Podfile and write pod “Cloudinary”.
2. Install pod in the project directory by using command “pod install”.
3. Open the project workspace not the project.
4. For swift, if you have bridging header file then write #import “Cloudinary/Cloudinary.h" in it otherwise. 
5. create one objective C file i.e .m file and then it will ask for creating the bridging header file click yes.
6. In that newly created .m file write #import “Cloudinary/Cloudinary.h”.
7. Create one swift file to write all the required methods for uploading the image to the cloudinary.
8. Configure the cloudinary url as  let cloudinary_url = “cloudinary://CLOUDINARY_API_KEY:CLOUDINARY_SECRET_KEY@CLOUD_NAME”.
9.In that swift file write upload method as 

func uploadImage(image: UIImage, onCompletion: (status: Bool, url: String?) -> Void) {

        let clouder = CLCloudinary(url:cloudinary_url)
        let forUpload = UIImagePNGRepresentation(image)
        let uploader:CLUploader = CLUploader(clouder, delegate: self)
        uploader.upload(forUpload, options: nil,
            withCompletion: { (dataDictionary: [NSObject: AnyObject]!, errorResult:String!, code:Int, context: AnyObject!) -> Void in
                self.uploadResponse = Mapper<ImageUploadResponse>().map(dataDictionary)
                if code < 400 { onCompletion(status: true, url: self.uploadResponse?.imageURL)}
                else {onCompletion(status: false, url: nil)}
            },
            andProgress: { (p1:Int, p2:Int, p3:Int, p4:AnyObject!) -> Void in
                print("Upload progress: %d/%d (+%d)",p2, p3, p1);
            }
        )
    }

10 . Call this uploadImage by using 
YOUR_CLASS_NAME.FUNCTION_NAME(UIIMAGE_INSTANCE, onCompletion: onCompletion) .

**Comment by Jean-PhilippeDESCAMPS** [comment]
Hi,

I'm trying to follow your guideline to integrating Cloudinary in swift using cocoapods.
I don't well interstanding the point 6, is it really necessary ? (And Why ?)
But it doesn't compile anyway.  It says in my new swift file, CLCloudinary(url...) Use of unresolved identifier. 

Any help ? 
Thanks

**Comment by nadavofi** [comment]
@Jean-PhilippeDESCAMPS Are you sure you have properly created the bridging header file?

**Comment by craigpearce5** [comment]
@neelamsharma12 using your code, is there a way to append tags to upload?

**Comment by manish-finoit** [comment]
@neelamsharma12  I have one doubt regarding Cloudinary Integrating in swift using cocoa pods. As in manual integration we have to add **libCloudinary.a** library but as per your steps you didn't mention  **libCloudinary.a** library. It is default adding while using cocoa pods or we don't need in case of cocoa pods.
Thanks

**Comment by phanisai4u** [comment]
private let cloudinary_url = "cloudinary://your:keysecret@name"
    
    func uploadImage(image: UIImage, onCompletion: (status: Bool, url: String?) -> Void) {
        
        let clouder = CLCloudinary(url:cloudinary_url)
        let forUpload = UIImagePNGRepresentation(image)
        let uploader:CLUploader = CLUploader(clouder, delegate: nil)
        uploader.upload(forUpload, options: nil, withCompletion: { (dataDir, error, code, contect) in
            if code < 400 {
                onCompletion(status: true,url: dataDir["url"] as? String ?? "")
            }else{
                onCompletion(status: false,url:"")
 
            }
        }) { (bytesSent, totalBytesSent, totalBytesExpectedToWrite, context) in
            print(bytesSent)
        }
        
    }

**Comment by jaysonng** [comment]
where can i find a proper tutorial on how to "safe mobile uploading" with how to generate the signature on your own server?

can't find how to get it to work or where to start even.

**Comment by pranav0705** [comment]
Hi,

I have a project in which I have to upload images to Cloudinary using swift. I was able to install cocoapods and as well as imported cloudinary files and was able to create a bridging header, but still it gives an error of  CLCloudinary(url...) Use of unresolved identifier. Any help would be much appreciated.

Thank you.

**Comment by phanisai4u** [comment]
in your podfile

       use_frameworks!

      target 'appname' do

      pod 'Cloudinary'
      end

      target 'appnameTests' do

        end

      target 'appnameUITests' do

      end
import Cloudinary package in your class as shown bellow


       import UIKit
       import Foundation
       import Cloudinary

    class CloudinaryHelper {
             static let sharedInstance = CloudinaryHelper()
    
                 private let cloudinary_url = "cloudinary://your:keysecret@name"

             func uploadImage(image: UIImage, onCompletion: (status: Bool, url: String?) -> Void) {

    let clouder = CLCloudinary(url:cloudinary_url)
    let forUpload = UIImagePNGRepresentation(image)
    let uploader:CLUploader = CLUploader(clouder, delegate: nil)
    uploader.upload(forUpload, options: nil, withCompletion: { (dataDir, error, code, contect) in
        if code < 400 {
            onCompletion(status: true,url: dataDir["url"] as? String ?? "")
        }else{
            onCompletion(status: false,url:"")

        }
    }) { (bytesSent, totalBytesSent, totalBytesExpectedToWrite, context) in
        print(bytesSent)
    }

}
}

**Comment by StevenArmandLee** [comment]
need an example on how to use token so that we can upload image securely

**Comment by nadavofi** [comment]
We've recently published new iOS libraries (version 2.0.0) written in SWIFT 3.0
https://github.com/cloudinary/cloudinary_ios Notice there's a Swift 2.3 dedicated brunch as well.

**Comment by IzaacBarratt** [comment]
When using the swift 2.3 version of cloudinary the pods dependency points to a version of Alamofire that is in swift 3. Is there a way I can manually change the pod dependency when installing?

**Comment by roeeba** [comment]
Hi @IzaacBarratt, I apologise for the late reply. Not sure if this is still relevant, but as a workaround, if you add Alamofire as a dependency to your own podfile (with the version you need, that works with swift 2.3) it will override Cloudinary's Alamo version. As long as you're using an Alamofire version with the same API this should work. That said, we'll further check this issue on our end.

**Comment by roeeba** [comment]
The issue was fixed and released. Closing.
