### ISSUE TITLE
Default image cache memory size is unlimited

### ISSUE THREAD

**Issue by shachar-silbert** [cloudinary/cloudinary_ios#200]
I have validated this in the past, becuase I have had these issues in my own apps.
I looked into problems with memory in my current app, and found out that the CLDImageCache.maxMemoryTotalCost has a setter.

However, the setter does not get called in the initial setting (Swift standard), and therefore the memoryCache object starts off as unlimited.

I should recommend adding the following line to the initializer, with a short comment:
maxMemoryTotalCost = Defines.defaultMemoryTotalCostLimit //Set the limit to validate the setter is called.

**Comment by shirlymanor** [comment]
Thank you for your feedback.
It's indeed an issue on our end and we are working on a fix.

**Comment by shirlymanor** [comment]
I wanted to update you that a fix for the issue was deployed.
Please let us know if that works for you.
