### ISSUE TITLE
Support for Swift 5

### ISSUE THREAD

**Issue by Sethmr** [cloudinary/cloudinary_ios#202]
I just upgraded to swift 5. Please upgrade your SDK so that this is not required.

`
   
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                if target.name == "Cloudinary" then
                    config.build_settings['SWIFT_VERSION'] = '4.2'
               end
            end
        end
    end
`

**Comment by yakirp** [comment]
Hi, 
We will update our SDK. I will update you when done.

Best

**Comment by roeeba** [comment]
@Sethmr The library was updated to support Swift 5.
