### ISSUE TITLE
Why can't we have class CLDUploadRequest public in iOS pod files.

### ISSUE THREAD

**Issue by avinashSminq** [cloudinary/cloudinary_ios#203]
Why can't we have class CLDUploadRequest in iOS pod files, I had a requirement to maintain a global request & assign the ongoing request to it, but due to the access being internal , I could not create a global object. Later i had to unlock pod file and make it public. So why can't we have it public. But i guess if i delete & re-install the pods my changes might go.  So why can't we have it public in future releases?

**Comment by shirlymanor** [comment]
CLDUploadRequest is public. You might want to try:

var globalRequst:CLDUploadRequest = cloudinary.createUploader().upload(...)

Please let me know if that answered your question and if not please provide a code snippet that we can investigate more.

**Comment by avinashSminq** [comment]
So I have an UploaderClass , where i create an upload request.
let uploadRequest =  cloudinary.createUploader().upload(...)
UploadManager.sharedInstance.uploaderRequest = uploadRequest

But I have a shared manager class to manage current upload. On creating an object it gives error: 
var uploaderRequest = CLDUploadRequest()
'CLDUploadRequest' initializer is inaccessible due to 'internal' protection level. 

The current declaration in pod file is:
@objcMembers open class CLDUploadRequest : NSObject {
  internal override init() {
    }
}
To fix my issue , i had to unlock pod files and make it pubic by:
@objcMembers open class CLDUploadRequest : NSObject {
    public init() {
    }
}
But as i delete and re install the pods , I have to change it again. Hence I wanted to have it declared public.

**Comment by shirlymanor** [comment]
For the use-case that described here, I believe that you don't need to create a new CLDUploadRequest from scratch. You can keep the reference to the one coming back from Uploader.upload(...).

Changing the pod himself is not a good idea because it will reset every time we release a new version. You can forks it and then there's a lot of manual work. Also, we wouldn't recommend to make the constructor public.
