### ISSUE TITLE
Cloudinary internal retry mechanism for iOS

### ISSUE THREAD

**Issue by avinashSminq** [cloudinary/cloudinary_ios#207]
I could not locate the parameter to set maximum number of retries for an upload in progress/ failed due to poor network. I am facing this issue because as soon as I disconnect my internet the upload waits but does not trigger any failure error. When i connect again to the internet , upload resumes. Just wanted to know whether cloudinary has internal retry / wait mechanism. I yes then please expose the class / parameter so that i can change around as per my requirement.

**Comment by shirlymanor** [comment]
That part of the networking is not on our SDK. When initializing the CLDCloudinary instance. The URLSessionConfiguration is an ios system type. You can read more about it here:
https://developer.apple.com/documentation/foundation/urlsessionconfiguration
