### ISSUE TITLE
Crash on version 2.7.0

### ISSUE THREAD

**Issue by LaurentiuUngur** [cloudinary/cloudinary_ios#208]
I've updated the library to latest version (**2.7.0**) and I get **EXC_BAD_ACCESS** when calling **createUrl()**. Has somebody same issue ? Thanks !

**Comment by idobarnoam** [comment]
Hey @LaurentiuUngur There's a sample app that we just recently published.

You can find it here: https://github.com/cloudinary/cloudinary-ios-sample-app/
It has only cloudinary on it and its working.

You can find it here: https://github.com/cloudinary/cloudinary-ios-sample-app/

Would you be able to share what's different between your project and that sample so we could start to pinpoint the issue?

**Comment by LaurentiuUngur** [comment]
I have an instance of `static let cloudinary = CLDCloudinary(configuration: CLDConfiguration(cloudName:)` and here's the code.

```
extension UIImageView {
    func setCloudinaryImage(with path: String?,
                            placeholder: UIImage? = nil,
                            contentMode: UIView.ContentMode = .scaleAspectFill,
                            size: CGSize? = nil) {
        self.image = placeholder
        self.clipsToBounds = true
        self.contentMode = contentMode

        guard let path = path else {
            return
        }

        let cloudinary = AppCore.cloudinary
        let urlGen = cloudinary.createUrl()

        if let size = size {
            let width = Int(size.width * UIScreen.main.scale)
            let height = Int(size.height * UIScreen.main.scale)
            let transformation = CLDTransformation().setWidth(width).setHeight(height).setCrop(.fit)

            urlGen.setTransformation(transformation)
        }

        guard let url = urlGen.setResourceType(.image).generate(path, signUrl: false) else {
            return
        }

        cloudinary.createDownloader().fetchImage(url) { [weak self] (image, _) in
            DispatchQueue.main.async {
                guard let image = image, let self = self else {
                    return
                }

                self.image = image
            }
        }
    }
}
```

Thanks for your help !

**Comment by strausr** [comment]
@LaurentiuUngur Looking at your implementation it works.

A couple of questions? 
* What line causes the crash
* What's the url your actually trying to fetch? 
* Your path variable may be wrong - you're using it as a public Id but it's called path so it seems strange/wrong. 
* You're replicating an existing cloudinary extension function instead of using the sdk for it, there's already an extension for UIImage called cldSetImage, you should use that. Usage example here https://github.com/cloudinary/cloudinary-ios-sample-app/blob/b07b39f9e8180b64b226f6ec7f4fcc2467b9f2e3/SampleApp/EffectsGalleryViewController.swift#L125

**Comment by LaurentiuUngur** [comment]
`urlGen.setTransformation(transformation)` is causing the crash.

<img width="1169" alt="Screenshot 2019-04-22 at 16 30 24" src="https://user-images.githubusercontent.com/13499785/56502717-fcb8c280-651b-11e9-82ea-11ac23294402.png">

**Comment by shirlymanor** [comment]
@LaurentiuUngur Can you try using the public id?
For example:

```
let transformation = CLDTransformation().setCrop(CLDTransformation.CLDCrop.scale).setWidth(350)
        let urlGen = cloudinary.createUrl().setTransformation(transformation).setResourceType(CLDUrlResourceType.image).generate("sample")!
```

**Comment by LaurentiuUngur** [comment]
Still same issue. It crashes when I'm trying to set the transformation

**Comment by shirlymanor** [comment]
EXC_BAD_ACCESS means that you are sending a message to an object that has already been released.
When I google it they suggested to use `static` in your declaration or try to clean the project and try again.
