### ISSUE TITLE
Unable to run the sample project 

### ISSUE THREAD

**Issue by ankit0812** [cloudinary/cloudinary_ios#209]
I am using Xcode 10.1
Most of the errors are in GradientCircularProgress (access level being private)

**Comment by idobarnoam** [comment]
Hi @ankit0812 
We have an updated sample app that you can find here:
https://github.com/cloudinary/cloudinary-ios-sample-app

Let us know if that helps?

**Comment by idobarnoam** [comment]
Hi @ankit0812 
I'm Closing this issue due to the time elapsed. 

Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
