### ISSUE TITLE
Alamofire dependency

### ISSUE THREAD

**Issue by AnthonyMillerSF** [cloudinary/cloudinary_ios#212]
Is there any way you guys would be willing to remove the Alamofire dependency sometime in the near future? 

I'm not a fan of having a third-party library I'm using also pull in a dependency on a large networking library that I'm not otherwise using into my code base.

Recent updates to `URLSession` make it much easier to work with than in the past.

**Comment by shirlymanor** [comment]
Thank you for the feedback, we will investigate this inquiry internally and will update you if we will decide to take this route.

**Comment by AnthonyMillerSF** [comment]
Thank you thank you thank you!
