### ISSUE TITLE
Incorrect URL format

### ISSUE THREAD

**Issue by michaelseanhansen** [cloudinary/cloudinary_ios#213]
When creating a transformation URL, the "generate" method seems to format the URL incorrectly. When concatenating videos, I'm getting a URL like this:

`https://<cloud_name>-res.cloudinary.com/video/upload/fl_splice,l_video:<video_b>/<video_a>`

This gives me an "Access Denied" error when trying to view it. But this URL works correctly:

`https://res.cloudinary.com/<cloud_name>/video/upload/fl_splice,l_video:<video_b>/<video_a>`

Here is a snippet that reproduces this:

```
let url = cloudinary.createUrl().setResourceType(.video)
let tra = CLDTransformation().setOverlay("video:<video_b>").setFlags("splice")
url.setTransformation(tra)
guard let str = url.generate("<video_a>") else {
    print("failed to generate")
    return
}

print("generated")
print(str)  // incorrect format
```

**Comment by leptians** [comment]
Hi Michael,

We will continue this investigation on the other ticket you opened.

Erwin Lukas
