### ISSUE TITLE
NSError domain: "com.cloudinary.error" - code: 400 0x0000000280a5ae80

### ISSUE THREAD

**Issue by Xcode09** [cloudinary/cloudinary_ios#216]
this error occurs when I upload the image to cloundinary why this happen

**Comment by roeeba** [comment]
Hi @Xcode09. To help us debug this, can you please share more details?

Please confirm which version of our SDK you're using, as well as:
* A sample of your code showing where the error occurs.
* The value you're passing as parameters (for example, the transformation options)
* The full error stack trace from your code, or the exact error message you see returned by our API

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
