### ISSUE TITLE
Invalid redeclaration of 'rangeAt'

### ISSUE THREAD

**Issue by ibrahimkteish** [cloudinary/cloudinary_ios#219]
I am getting `Invalid redeclaration of 'rangeAt'` when I am trying to build the project with cocoapod and Xcode 10.3 Swift 5.0 in the `CLDCompatibility.swift` file

**Comment by shirlymanor** [comment]
In order to reproduce this issue can you please share the pod file that you are using? If privacy is an issue please open a ticket at support@cloudinary.com

**Comment by ibrahimkteish** [comment]
I have deleted the Pod folder and run `pod install` everything worked as expected :) @shirlymanor

**Comment by shirlymanor** [comment]
Great, thanks for the update!
