### ISSUE TITLE
Null when non-null required

### ISSUE THREAD

**Issue by tapz** [cloudinary/cloudinary_ios#22]
In Xcode 7 there are 4 warnings:

CLUploader.m: 301-305
Null passed to a callee that requires a non-null argument

**Comment by meandkareem** [comment]
same here

**Comment by TalLevAmi** [comment]
Please check if d5a558e1eb118c55483c0e0fdb3598484d212e8d solves the issue for you.

**Comment by TalLevAmi** [comment]
solved in 1.0.14
