### ISSUE TITLE
Getting error on pod  Installation.

### ISSUE THREAD

**Issue by ZawarAli6** [cloudinary/cloudinary_ios#222]
Got this error while installing pods and I have only one version of xcode.

[!] /bin/bash -c 
set -e
swift ./CLDCrypto/GenerateCLDCryptoModule.swift iphonesimulator .
swift ./CLDCrypto/GenerateCLDCryptoModule.swift iphoneos .

./CLDCrypto/GenerateCLDCryptoModule.swift:15:34: error: 'characters' is unavailable: Please use String directly
    let args: [String] = command.characters.split { $0 == " " }.map(String.init)
                                 ^~~~~~~~~~
Swift.String:5:16: note: 'characters' was obsoleted in Swift 5.0
    public var characters: String { get set }
               ^

**Comment by michalkcloudinay** [comment]
Hi @ZawarAli6,
You are using an old version, you need to update the version of the SDK.

**Comment by ZawarAli6** [comment]
> Hi @ZawarAli6,
> You are using an old version, you need to update the version of the SDK.
 I am using Cloudinary 2.0.3.

**Comment by ZawarAli6** [comment]
<img width="571" alt="Screen Shot 2019-12-26 at 5 29 57 PM" src="https://user-images.githubusercontent.com/51619135/71554743-452e6580-2a45-11ea-920b-0075a4c5bf1b.png">

**Comment by michalkcloudinay** [comment]
Hi, @ZawarAli6  The current version is 2.8.0.
