### ISSUE TITLE
Recorded Audio not able to send

### ISSUE THREAD

**Issue by karthisiva** [cloudinary/cloudinary_ios#223]
As per the requirement, We have record some audio and that has to be send to Cloudinary. We are not able to accomplish this. Kindly check my codes. Here we totally confused about **resource_type**

    public func uplodaMedia(resource : String,_ controller: UIViewController, _ data:Data, kuwyId :String, fileName : String, complition:@escaping (String) -> Void ){
        var objParams = [String : AnyObject]()
        objParams["folder"] = cloudinaryPath as AnyObject
        objParams["publicId"] = fileName as String as AnyObject
        objParams["tags"] = kuwyId as AnyObject
                 
        if resource == "A"{
            objParams["resource_type"] = "raw" as AnyObject
        }else{
            objParams["resource_type"] = "video" as AnyObject
        }
        controller.view.isUserInteractionEnabled = false
        cld.createUploader().upload(data: data, uploadPreset:AppDelegate.uploadPreset , params: CLDUploadRequestParams(params: objParams) , progress: { (progress) in
         }) { (result, error) in
            if let error = error {
                print("Error uploading image %@", error)
                controller.view.isUserInteractionEnabled = false
                complition("false")
            } else {
                controller.view.isUserInteractionEnabled = true
                if let result = result{
                    if let url = result.url{
                        complition(url)
                    }
                }
             }
        }
        
    }

    fileprivate func uploadAudio(data : Data, sender : UIButton){
        self.showLoader()
        
        
        self.serviceRequest.uplodaMedia(resource: "A", self, data, kuwyId: kuwy_ID, fileName: "Home FI") { (uploadedUrl) in
            print("final image url------->\(uploadedUrl)")
            self.hideLoader()
            if uploadedUrl == "false"{
                
            }else{
              switch sender {
              case self.btnAudio1:
                  self.audioUrl1 = uploadedUrl
                         break
              case self.btnPhoto2:
                  self.audioUrl2 = uploadedUrl
                  break
              default:
                  break
              }
            }
        }

do {
                    let imageData = try Data(contentsOf: fileUrl as URL)
                    audioData1 = imageData
                    self.uploadAudio(data: audioData1, sender: btnAudio1)
                    btnAudio1.backgroundColor = Constants.buttonSelectedColor
                    btnAudio1 .setTitleColor(Constants.selectedTextColor, for: .normal)
                } catch {
                    print("Unable to load data: \(error)")
                }

Receving the following error:

**Error uploading image %@ Error Domain=com.cloudinary.error Code=400 "(null)" UserInfo={message=Invalid image file}**

**Comment by aleksandar-cloudinary** [comment]
Hi @karthisiva. Audio files should be uploaded with `resource_type` set to 'video'. Omitting the `resource_type` parameter defaults it to 'image' and that is why you are seeing the error. You can either explicitly set audio files to have a `resource_type` of 'video' or alternatively, set it to 'auto where Cloudinary would automatically determine and set the `resource_type`. Please let me know how that goes.

**Comment by karthisiva** [comment]
Thanks for your quick reply, As you said i have already tested with **auto, raw, video** But still same issue occurring. See my request params.

var objParams = [String : AnyObject]()
    objParams["folder"] = cloudinaryPath as AnyObject
    objParams["publicId"] = fileName as String as AnyObject
    objParams["tags"] = kuwyId as AnyObject
             
    if resource == "A"{
        objParams["resource_type"] = "raw" as AnyObject
       //objParams["resource_type"] = "video" as AnyObject
//objParams["resource_type"] = "auto" as AnyObject
    }else{
        objParams["resource_type"] = "video" as AnyObject
    }

**Comment by karthisiva** [comment]
**Cloudinary would automatically determine and set the resource_type** Thanks @aleksandar-cloudinary  for this statement. working added

 public func uplodaMedia(resource : String,_ controller: UIViewController, _ data:Data, kuwyId :String, fileName : String, complition:@escaping (String) -> Void ){        
        let params = CLDUploadRequestParams()
        .setPublicId(fileName)
            .setTags(kuwyId)
            .setFolder(cloudinaryPath)
            .setResourceType("video")

        controller.view.isUserInteractionEnabled = false
        cld.createUploader().upload(data: data, uploadPreset:AppDelegate.uploadPreset , params: params as? CLDUploadRequestParams , progress: { (progress) in
         }) { (result, error) in
            if let error = error {
                print("Error uploading image %@", error)
                controller.view.isUserInteractionEnabled = true
                complition("false")
            } else {
                controller.view.isUserInteractionEnabled = true
                if let result = result{
                    if let url = result.url{
                        complition(url)
                    }
                }
             }
        }
        
    }
