### ISSUE TITLE
Update to iOS9

### ISSUE THREAD

**Issue by lsolniczek** [cloudinary/cloudinary_ios#23]
Hi, will you plan to update syntax to iOS9?

**Comment by tocker** [comment]
We need to maintain backward compatibility for other users, so we tread with caution.

Having said that, this is an open source project, so feel free to fork and hack :smiley: 

Pull requests are also welcome!

**Comment by Yinten** [comment]
Will this work with Swift?

**Comment by nadavofi** [comment]
@Yinten Do you mean the current SDK?
Indeed it's available for Swift using cocoa-pods. See issue #20.

**Comment by nadavofi** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
