### ISSUE TITLE
How to do a background upload using background modes

### ISSUE THREAD

**Issue by BossOz** [cloudinary/cloudinary_ios#231]
Could you please provide example how to use Cloudinary API for uploading/downloading media using background modes?
I would like to let the user to move the app to the background and continue my task.
Thank you

**Comment by michalkcloudinay** [comment]
Hey @BossOz , By default, uploading with the IOS SDK  is with background support.
You can read more about this here: https://cloudinary.com/documentation/ios_image_and_video_upload

**Comment by BossOz** [comment]
So Cloudinary SDK is managing the App suspension stuff by itself?
[https://developer.apple.com/documentation/foundation/url_loading_system/downloading_files_in_the_background](https://developer.apple.com/documentation/foundation/url_loading_system/downloading_files_in_the_background)

**Comment by shirlymanor** [comment]
@BossOz yes

**Comment by BossOz** [comment]
Is it possibile to have more details about it?
I would like to know, in detail, what's happen when I'm uploading an image to cloudinary and the user move the app to the background. 
If the upload is stopped by iOs, there will be an error message?

In the link provided by @michalkcloudinay there is nothing that talk about that.
Thank you

**Comment by shirlymanor** [comment]
@BossOz We are using the default URLSessionConfiguration and the default behavior as in the document that you've shared.
When the system suspend the app ( app is in the background) while some process is performed in another process. 
when the process finishes, the system resumes and calls the UIApplicationDelegate

**Comment by BossOz** [comment]
Perfect! 
Thank you!

**Comment by BossOz** [comment]
What is/are the parameter/s we need to enabled in order to have the background modes working?

![Schermata 2020-04-13 alle 12 16 48](https://user-images.githubusercontent.com/4025510/79113198-a7a33b80-7d80-11ea-95fa-ea26f47669a6.png)

**Comment by shirlymanor** [comment]
@BossOz you don't need any of those params for background url sessions.
