### ISSUE TITLE
Delete image/video/raw file from cloudinary !!

### ISSUE THREAD

**Issue by Yagnik13** [cloudinary/cloudinary_ios#239]
Hello team,

Please guide me how to delete specific file(image/video/raw) from cloudinary?

**Comment by shirlymanor** [comment]
Sure, you can use our admin API. For example:
https://github.com/cloudinary/cloudinary_ios/blob/da9e948e29d573904b3e7f4d98cadbdc8b06ecf9/Example/Tests/NetworkTests/ManagementApiTests.swift#L387

```
func destroyAsset()
{
    let params = CLDDestroyRequestParams().setInvalidate(true).setResourceType(CLDUrlResourceType.auto)
    cloudinary.createManagementApi().destroy("my-wordpress-folder/sample-6", params: params).response({ (resultRes, errorRes) in
        print(resultRes?.result)
           })
}
```
