### ISSUE TITLE
unable to import into swift 5 project

### ISSUE THREAD

**Issue by Eshan-T** [cloudinary/cloudinary_ios#245]
## Bug report for Cloudinary iOS SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two.
…

## Issue Type (Can be multiple)
[ !!] Build - Can’t install or import the SDK
[ ] Performance - Performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Other (Specify)

## Steps to reproduce
'import Cloudinary'  in the pod file gives this error while doing pod install

"set -e
swift ./CLDCrypto/GenerateCLDCryptoModule.swift iphonesimulator .
swift ./CLDCrypto/GenerateCLDCryptoModule.swift iphoneos .

./CLDCrypto/GenerateCLDCryptoModule.swift:15:34: error: 'characters' is unavailable: Please use String directly
    let args: [String] = command.characters.split { $0 == " " }.map(String.init)
                                 ^~~~~~~~~~
Swift.String:5:16: note: 'characters' was obsoleted in Swift 5.0
    public var characters: String { get set }"

-- I suppose this is because 2.0.3 was not swift 5 compatible so importing 2.9.0 should fix this--

and when changing pod file to : pod 'Cloudinary', '~> 2.9.0'
then the error is:

[!] CocoaPods could not find compatible versions for pod "Cloudinary":
  In Podfile:
    Cloudinary (~> 2.9.0)

## Error screenshots or Stack Trace (if applicable)
…

## Build/Dependency management
[ ] Cocoa-Pods
[ ] Carthage
[ ] Manual import
[ ] Other (Specify)

## Is the issue reproducible only on a specific device?
[ !!] No
[ ] Yes (specify model + iOS version)

## Versions and Libraries (fill in the version numbers)
iOS Cloudinary SDK version - 2.0.3/ 2.9.0
OSX (on the dev environment) - 10.15
XCode - 11.5
Swift - 5.0
Target iOS - 0.0.0

Repository
If possible, please provide a link to a reproducible repository that showcases the problem

**Comment by shirlymanor** [comment]
Can you please share your entire podfile?
you can also try running an empty project with just this dependency to make sure it's working.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com, or create a new ticket if you have any additional issues.
