### ISSUE TITLE
Update Library for Swift?

### ISSUE THREAD

**Issue by grantkemp** [cloudinary/cloudinary_ios#26]
Hi @TalLevAmi  do you guys have an updated library coming up that doesn't need a wrapper for swift? ( and ideally works on Mac OSx too?) 

Would be fab as it will make it easier to build Cloudinary into other apps. 

Cheers

**Comment by TalLevAmi** [comment]
We are working on an improved iOS library that will have better Swift integration. We'll update when we have something ready for people to play with.

**Comment by grantkemp** [comment]
Cool good to know.  But I have got it working ok via Rest api
