### ISSUE TITLE
Error while trying to get image from server

### ISSUE THREAD

**Issue by nhokkuteluv** [cloudinary/cloudinary_ios#27]
Sometimes I got this exception:
-[CLCloudinary finalizePrefix:options:]: message sent to deallocated instance 0x7f9dea984110.
It seems send message to deallocated instance while trying to contact to server to get image? Can anybody help with this effort?

**Comment by TalLevAmi** [comment]
finalizePrefix:options is part of building of the URL. It is done before any communication to the service. 
A couple of useful links to try to solve this:
1) http://stackoverflow.com/questions/13018251/how-do-i-avoid-a-zombies-error-with-xcode-4-5-w-o-arc/14734241#14734241
2) https://developer.apple.com/library/ios/recipes/Instruments_help_articles/FindingMessagesSenttoDeallocatedObjects/FindingMessagesSenttoDeallocatedObjects.html

**Comment by nhokkuteluv** [comment]
Thank you! TalLevAmi, very kind of u!
