### ISSUE TITLE
`url:source:options` not working properly - generating back urls

### ISSUE THREAD

**Issue by Xyand** [cloudinary/cloudinary_ios#28]
Recently I've stumbled into a critical problem when transformation links are generated incorrectly. Example:

    http://res.cloudinary.com/XXXXX/image/upload/c_fill,h_1200,w_1800/http://res.cloudinary.com/XXXXX/image/upload/v1445690732/a2wa6cixde3bqf7d8hdc.jpg

Instead of:

    http://res.cloudinary.com/XXXXX/image/upload/c_fill,h_1200,w_1800/v1445690732/a2wa6cixde3bqf7d8hdc.jpg

It used to work once but now it's corrupted in production (AppStore). What changed between released is cloudinary_ios 1.0.12 --> 1.0.13, XCode version and iOS version.

When calling `url:source:options` I'm sending the complete URL as `source`: 

    http://res.cloudinary.com/XXXXX/image/upload/v1445690732/a2wa6cixde3bqf7d8hdc.jpg

I tried revering back to 1.0.12 but it still doesn't work. After inspecting the code it seems to me that the regex used is wrong as it doesn't allow the http part of the url. 

    @"^([^/]+)/([^/]+)/v([0-9]+)/([^#]+)(#[0-9a-f]+)?$"

Omitting '^' seems to do the trick. I have idea how it used to work previously and would really appreciate your feedback on this one.

**Comment by nadavofi** [comment]
The `source` attribute must only contain the `public_id` of the resource.
It can also contain the `version` and the `format` extension, although those can also be provided using `options` params

Some samples are available here:
https://github.com/cloudinary/cloudinary_ios/blob/master/CloudinaryTests/CloudinaryTests.m#L539

resource accepts the whole URL only in case of fetch, e.g.:
https://github.com/cloudinary/cloudinary_ios/blob/master/CloudinaryTests/CloudinaryTests.m#L430

Hope it clarifies the issue.

**Comment by Xyand** [comment]
Thanks for the quick answer.

This is very strange as it used to work. Anyhow, would you consider changing the SDK to support full URLs? 

In our app we store only the URL to the uploaded file and then use it to generate derived images. Of course I can parse the URL myself before calling `url:source:options` but it just feels odd as all the information is available.

**Comment by neelamsharma12** [comment]
@Xyand when you upload the image to the Cloudinary you get "public_id" and "format" in response if you are not providing them explicitly. So you can use that "public_id" and "format" to get the correct URL Firstly,  create one string as 

let imageString = uploadResponse.publicId?.stringByAppendingString("." + uploadResponse.format!) 
// imageString will be like "a2wa6cixde3bqf7d8hdc.jpg" in your case

and then use  this obtained imageString for getting the correct transformation URL like this,

let transformUrl = cloudinary.url(imageString, options: ["transformation":transformation!])
