### ISSUE TITLE
'Must supply cloud_name in tag or in configuration': Issue when get image

### ISSUE THREAD

**Issue by nhokkuteluv** [cloudinary/cloudinary_ios#30]
I got exception such as 'Must supply cloud_name in tag or in configuration'. It sometimes throws exception in spite of I I supply needed information at instantiate stage. Can any body explain why and how to avoid this? Thank you very much

**Comment by neelamsharma12** [comment]
@nhokkuteluv  If you are an authenticated user then for uploading the image or any file you need to configure the cloudinary(Object of CLCloudinary) by using

cloudinary?.config().setValue(YOUR_CLOUD_NAME, forKey:"cloud_name").

**Comment by nadavofi** [comment]
Once a CLCloudinary instance is initialized using your credentials, and based on it a CLUploader instance is initialized, the CLUploader can be used without the need to explicitly provide your cloud-name. For example:

    CLCloudinary *cloudinary = [[CLCloudinary alloc] initWithUrl: @"cloudinary://123456789012345:abcdeghijklmnopqrstuvwxyz12@n07t21i7"];
    CLUploader* uploader = [[CLUploader alloc] init:cloudinary delegate:self];

Feel free to share with us a code snippet, via [private thread](http://support.cloudinary.com/hc/en-us/requests/new), for further assistance if needed.
