### ISSUE TITLE
Can't upload picture

### ISSUE THREAD

**Issue by lewisbwl** [cloudinary/cloudinary_ios#31]
I am trying to upload an image and keep getting an error while trying to upload an image.

Here is the code I am trying to use:
func createFeedItem(imageURL: NSURL) {
        let data = NSData(contentsOfURL: imageURL)
        let uploader:CLUploader = CLUploader(cloudinary, delegate: self)
        
        let options: [NSObject : AnyObject] = ["test" : "test"]
        uploader.upload(data, options: options,
            withCompletion: { (result, error, code, context) -> Void in
                
                let formatParam = result["format"] as? String
                let heightParam = result["height"] as? CGFloat
                let widthParam = result["width"] as? CGFloat
                let publicIdParam = result["public_id"] as? String
                let resourceTypeParam = result["resource_type"] as? String
                let secureURLParam = result["secure_url"] as? String
                let signatureParam = result["signature"] as? String
                let urlParam = result["url"] as? String
                let versionParam = result["version"] as? Int

                if let format = formatParam, height = heightParam, width = widthParam, publicId = publicIdParam, resourceType = resourceTypeParam, secureURLString = secureURLParam, secureURL = NSURL(string: secureURLString), signature = signatureParam, urlString = urlParam, url = NSURL(string: urlString), version = versionParam  {
                    let size = CGSizeMake(width, height)
                    let imageInfo = ImageInfo(format: format, size: size, publicId: publicId, resourceType: resourceType, secureURL: secureURL, signature: signature, url: url, version: version)
                    let feedItem = FeedItem(feedItemId: "", version: 0, imageInfo: imageInfo, likes: nil, annotations: nil)
                    self.feedItems.append(feedItem)
                    NSNotificationCenter.defaultCenter().postNotificationName(SCFeedItemAddedNotification, object: self, userInfo: ["feedItem" : feedItem])
                }
            },
            andProgress: {(bytesWritten, totalBytesWritten, totalBytesExpectedToWrite, context) -> Void in
                print("Progressing on download")
            }
        )
    }

I get the following error which seems to point to the fact that one of the categories that are in the library is not found:

2015-12-05 22:27:11.838 Lookieo[21622:4457872] -[_TtGCSs29_NativeDictionaryStorageOwnerCSo8NSObjectPSs9AnyObject__ cl_valueForKey:defaultValue:]: unrecognized selector sent to instance 0x7ffbf15b4f30
2015-12-05 22:27:11.843 Lookieo[21622:4457872] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_TtGCSs29_NativeDictionaryStorageOwnerCSo8NSObjectPSs9AnyObject__ cl_valueForKey:defaultValue:]: unrecognized selector sent to instance 0x7ffbf15b4f30'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001102f2f45 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000112382deb objc_exception_throw + 48
	2   CoreFoundation                      0x00000001102fb56d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x0000000110248eea ___forwarding___ + 970
	4   CoreFoundation                      0x0000000110248a98 _CF_forwarding_prep_0 + 120
	5   Lookieo                             0x000000010fc82204 -[CLUploader buildUploadParams:] + 2084
	6   Lookieo                             0x000000010fc7b137 -[CLUploader upload:options:withCompletion:andProgress:] + 263
	7   Lookieo                             0x000000010fc5f283 _TFC7Lookieo16ServiceConnector14createFeedItemfS0_FCSo5NSURLT_ + 1491
	8   Lookieo                             0x000000010fc5c084 _TFFC7Lookieo28FeedCollectionViewController15prepareForSegueFS0_FTCSo17UIStoryboardSegue6senderGSqPSs9AnyObject___T_U_FGSqCSo5NSURL_T_ + 148
	9   Lookieo                             0x000000010fc5c177 _TTRXFo_oGSqCSo5NSURL__dT__XFo_iT8imageURLGSqS____iT__ + 23
	10  Lookieo                             0x000000010fc5aa81 _TPA__TTRXFo_oGSqCSo5NSURL__dT__XFo_iT8imageURLGSqS____iT__ + 81
	11  Lookieo                             0x000000010fc6b8ae _TFFC7Lookieo35ChoosePhotoCollectionViewController14collectionViewFS0_FTCSo16UICollectionView24didSelectItemAtIndexPathCSo11NSIndexPath_T_U_FTGSqCSo6NSData_GSqSS_OSC18UIImageOrientationGSqGVSs10DictionaryCSo8NSObjectPSs9AnyObject____T_ + 830
	12  Lookieo                             0x000000010fc6bb33 _TTRXFo_oGSqCSo6NSData_oGSqSS_dOSC18UIImageOrientationoGSqGVSs10DictionaryCSo8NSObjectPSs9AnyObject____dT__XFdCb_dGSqS__dGSqCSo8NSString_dS0_dGSqCSo12NSDictionary__dT__ + 419
	13  Photos                              0x0000000110d5ca7c __65-[PHImageManager requestImageDataForAsset:options:resultHandler:]_block_invoke1634 + 519
	14  AssetsLibraryServices               0x000000011630a762 __pl_dispatch_async_block_invoke + 25
	15  libdispatch.dylib                   0x0000000112e6de5d _dispatch_call_block_and_release + 12
	16  libdispatch.dylib                   0x0000000112e8e49b _dispatch_client_callout + 8
	17  libdispatch.dylib                   0x0000000112e762af _dispatch_main_queue_callback_4CF + 1738
	18  CoreFoundation                      0x00000001102532e9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	19  CoreFoundation                      0x00000001102148a9 __CFRunLoopRun + 2073
	20  CoreFoundation                      0x0000000110213e08 CFRunLoopRunSpecific + 488
	21  GraphicsServices                    0x0000000116a57ad2 GSEventRunModal + 161
	22  UIKit                               0x0000000110e7b30d UIApplicationMain + 171
	23  Lookieo                             0x000000010fc5dcbd main + 109
	24  libdyld.dylib                       0x0000000112ec292d start + 1
	25  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by TalLevAmi** [comment]
Please go to your XCode project settings,
Under the Linker section go to "Other Linker Flags" and add -ObjC

**Comment by neelamsharma12** [comment]
Please check these things :
1.In  options set one other parameter as ["runLoop": true]
2. In other Linker flag add -ObjC and -($inherited) and install your pod again if you are integrating by using CocoaPods.
3.Could you please verify once whether your options: [NSObject : AnyObject] = ["test" : "test"] is correct.

**Comment by taragano** [comment]
@lewisbwl - Do you still experience this issue?
As it's been a while since the last response, I'll close this issue now, but please feel free to re-open it if you need any further assistance.

Thanks,
Itay
