### ISSUE TITLE
Cloudinary 2.10.1 with SPM is not compiling

### ISSUE THREAD

**Issue by LaurentiuUngur** [cloudinary/cloudinary_ios#325]
## Bug report for Cloudinary iOS SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two.

Project is not compiling due to missing imports into Cloudinary 

`CLDQualityAnalysis` - should `import Foundation`
`CLDCropScrollViewController` - should `import UIKit`
`CLDCropViewCalculator`- should `import UIKit`

<img width="1354" alt="Screenshot 2021-02-06 at 08 14 12" src="https://user-images.githubusercontent.com/13499785/107110789-6e7a1180-6853-11eb-8802-a6ff64fa26dc.png">

## Issue Type (Can be multiple)
[X] Build - Can’t install or import the SDK
[ ] Performance - Performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Other (Specify)

## Build/Dependency management
[ ] Cocoa-Pods
[ ] Carthage
[ ] Manual import
[X] SPM

## Is the issue reproducible only on a specific device?
[X] No
[ ] Yes (specify model + iOS version)

## Versions and Libraries (fill in the version numbers)
iOS Cloudinary SDK version - 2.10.1
OSX (on the dev environment) - 11.2
XCode - 12.4
Swift - 5.3
Target iOS - 14

Repository
If possible, please provide a link to a reproducible repository that showcases the problem

**Comment by michalkcloudinay** [comment]
Hi @LaurentiuUngur, Thanks for reporting this issue, we have opened an internal request to fix this. In the meantime, please use the version you were using before the update.

**Comment by gonzalonunez** [comment]
+1 this is happening to me as well! Happy to help if needed :)

**Comment by MattNewberry** [comment]
It appears this was fixed with e3053a9a14cca37e43b6542ddc849e0b5a281531... can you all push a new release?

**Comment by asisayag2** [comment]
A new version will be published soon

**Comment by dannyhertz** [comment]
Any updates on this? We are also waiting on the fixes SPM release.

**Comment by momoip** [comment]
Hi dannyhertz,
Thanks for your patience.  We will try to release a new version soon.

**Comment by anonrig** [comment]
![image](https://user-images.githubusercontent.com/1935246/116061683-d3434c00-a68b-11eb-9c78-e4e7c803f409.jpeg)

I expect this behavior from a non-profit organization but not from...

**Comment by michalkcloudinay** [comment]
A new version was released (version 3.0.0) with a fix for this issue. Please let us know if you have any issues.
