### ISSUE TITLE
Missing OperationQueue name

### ISSUE THREAD

**Issue by gigisommo** [cloudinary/cloudinary_ios#332]
## Bug report for Cloudinary iOS SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two.
The operation queues have an empty name. Could you add a name to the queues created in:
- CLDAsyncNetworkUploadRequest
- CLDDefaultNetworkAdapter
- CLDFetchImageRequestImpl
- CLDNTaskDelegate
- CLDUploadRequestWrapper

Having a name will help debugging. It gets also reported in stack traces in case of a crash.

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Performance - Performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[x] Other (Specify) - Hard to debug crashes and issues

**Comment by michalkcloudinay** [comment]
Hi @gigisommo, thanks for contacting us. We have opened an internal request for this inquiry and we will update you with any new information.

**Comment by const-cloudinary** [comment]
Fixed in #333
