### ISSUE TITLE
Crash on update version 2.9.0 to 3.0.0

### ISSUE THREAD

**Issue by ChechkovEugene** [cloudinary/cloudinary_ios#339]
## Bug report for Cloudinary iOS SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two.
Carthage crashes on update version 2.9.0 to 3.0.0

## Issue Type (Can be multiple)
[ x] Build - Can’t install or import the SDK
[ ] Performance - Performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Other (Specify)

## Steps to reproduce
Regular carthage using

## Error screenshots or Stack Trace (if applicable)

note: Using new build system
note: Building targets in parallel
note: Using codesigning identity override: 
note: Planning build
note: Constructing build description
error: /Project/Carthage/Checkouts/cloudinary_ios/Example/Pods/Target Support Files/Cloudinary/Cloudinary.release.xcconfig: unable to open file (in target "Cloudinary" in project "Pods") (in target 'Cloudinary' from project 'Pods')
error:  /Project/Carthage/Checkouts/cloudinary_ios/Example/Pods/Target Support Files/Cloudinary/Cloudinary.release.xcconfig: unable to open file (in target "Cloudinary" in project "Pods") (in target 'Cloudinary' from project 'Pods')
error: */Carthage/Checkouts/cloudinary_ios/Example/Pods/Target Support Files/Cloudinary/Cloudinary.release.xcconfig: unable to open file (in target "Cloudinary" in project "Pods") (in target 'Cloudinary' from project 'Pods')

## Build/Dependency management
[ ] Cocoa-Pods
[x] Carthage
[ ] Manual import
[ ] Other (Specify)

## Is the issue reproducible only on a specific device?
[ x] No
[ ] Yes (specify model + iOS version)

## Versions and Libraries (fill in the version numbers)
iOS Cloudinary SDK version - 3.0.0
OSX (on the dev environment) - 11.2.3
XCode - 12.4.0
Swift - 5.0.0
Target iOS - 14.2.0

Repository
If possible, please provide a link to a reproducible repository that showcases the problem

**Comment by michalkcloudinay** [comment]
Hi @ChechkovEugene, thanks for reporting this issue. We will check this and get back to you with more insights.

**Comment by michalkcloudinay** [comment]
Hi @ChechkovEugene, a new version with a fix for this issue was released. Let us know if you have any further issues. Thanks
