### ISSUE TITLE
Can't upload image using Asset URL

### ISSUE THREAD

**Issue by railsfactory-pavankumarc** [cloudinary/cloudinary_ios#34]
I'm trying to upload the image / video from the Asset url (fetched from the gallery/camera image/video) but there is crash..

Please let me know how can i resolve this issue in Objective C.

**Comment by nadavofi** [comment]
@railsfactory-pavankumarc Can you share more information?
The exact error message and the stack-trace can be useful.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
