### ISSUE TITLE
Search API in iOS SDK

### ISSUE THREAD

**Issue by Saurabh-vegans** [cloudinary/cloudinary_ios#341]
## Feature request for Cloudinary iOS SDK
- I will suggests to have a Search API integration inside ManagementAPI to fetch list of videos/images by folder or tags to show them collectively as a preview from where user can download that particular resource.

## Explain your use case
- Current Use case is to download all videos by folder, so that I can prefetch those videos and can download all videos from that folder without knowing the public-id of each video which can help me to make app independent of number of videos and I can update video in Cloud, which reflects in app without publishing any new ipa or apk.

NOTE:- Better to have this same feature in Android SDK as well. As I m iOS developer - don't know if android SDK already supports this.

**Comment by roeeba** [comment]
Hi @Saurabh-vegans, For creating Search or Admin APIs requests an API_Secret key is needed. That is why it's not available in our client-side/mobile SDKs as exposing this key will put your account at risk. Please use one of our server-side libraries for such requests (e.g., Ruby, PHP, Node, etc).

**Comment by Saurabh-vegans** [comment]
> Hi @Saurabh-vegans, For creating Search or Admin APIs requests an API_Secret key is needed. That is why it's not available in our client-side/mobile SDKs as exposing this key will put your account at risk. Please use one of our server-side libraries for such requests (e.g., Ruby, PHP, Node, etc).

I know - I even tried it, but better to have this solution in app. for example - what if someone doesn't have any backend and just wanted to use Cloudinary as backend for videos?

**Comment by d-mendoza** [comment]
@Saurabh-vegans There may be alternatives to Search API to pull a list assets that are on your account. It would be nice to have that Search API functionality, but as Roee mentioned, it's a design issue that's a standard amount backend and client-side logic. For instance, you can pull a list of assets that are tagged on Cloudinary using client resource lists here https://cloudinary.com/documentation/advanced_url_delivery_options#client_side_asset_lists. If you like, we can discuss your use-case further via a support ticket here:
https://support.cloudinary.com/hc/en-us/requests/new

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at [https://support.cloudinary.com/hc/en-us/requests/new](http://support.cloudinary.com/) or create a new ticket if you have any additional issues.
