### ISSUE TITLE
Can I upload videos?

### ISSUE THREAD

**Issue by rinat-enikeev** [cloudinary/cloudinary_ios#35]
Hi, can I upload videos using this sdk? 
Thanks.

**Comment by mitchellporter** [comment]
Yes, you can.

**Comment by taragano** [comment]
As @mitchellporter said, Yes, of course :)
In order to upload a video file, set the `resource_type` parameter to `video`:

```
CLUploader* uploader = [[CLUploader alloc] init:cloudinary delegate:self];
[uploader upload:[self file] options:@{@"resource_type": @"video"}];
```

**Comment by rinat-enikeev** [comment]
@taragano thank you. 
For somebody reading this question:
Btw, cloudinary also creates preview image for uploaded video: 
[NSString stringWithFormat:@"http://res.cloudinary.com/%@/video/upload/%@.jpg", cloudinary_name, cloudinary_id];

**Comment by nadavofi** [comment]
@rinat-enikeev Note that you can also use the url() helper method to generate the preview image:

```
    CLTransformation* transformation = [CLTransformation transformation];
    [transformation setFetchFormat:@"jpg"];
    NSString* result = [cloudinary url:video_id options:@{@"transformation": transformation, @"resource_type": @"video"}];
```
