### ISSUE TITLE
Support of "opacity" is missing from the sdk

### ISSUE THREAD

**Issue by gasthana0** [cloudinary/cloudinary_ios#36]
As per the api doc you can pass [opacity](http://cloudinary.com/documentation/image_transformations#opacity_parameter)  to transform the image, but sdk doesn't support opacity param.

**Comment by Shivam101** [comment]
Opacity still doesn't seem to be supported on the sdk.

**Comment by taragano** [comment]
Thank you for response,
Our team is constantly working on maintaining and extending our SDKs.
Opacity is on our road-map to support, we apologize for the inconvenience.

**Comment by taragano** [comment]
Please update to the latest version, which includes lots of improvements, including the opacity parameter.
Please let me know if it works for you?

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
