### ISSUE TITLE
Crop property is read-only, setCrop method is not exposed in header

### ISSUE THREAD

**Issue by Arcanfel** [cloudinary/cloudinary_ios#39]
In CLTransformation.h there is a crop property:
`@property NSString *crop`

However, the setter method:
`- (void)setCrop:(NSString *)value { [self param:@"crop" value:value]; }`
is only defined in .m file and not exposed the in the header.

**Comment by TalLevAmi** [comment]
setCrop is a standard setter exposed by the crop property itself.
You can see it used here - https://github.com/cloudinary/cloudinary_ios/blob/master/CloudinaryTests/CloudinaryTests.m#L132
