### ISSUE TITLE
Error: `method '...' not exposed to Objective-C`

### ISSUE THREAD

**Issue by robingenz** [cloudinary/cloudinary_ios#391]
## Describe the bug in a sentence or two.

I want to use the Cloudinary iOS SDK in a project where I need to export my Swift class to Objective-C ([Read more](https://capacitorjs.com/docs/v2/plugins/ios#export-to-capacitor)).
Unfortunately, I get the following two errors in `Pods/Cloudinary/ios/CLDCropView.swift` when building the project:
```
Argument of '#selector' refers to instance method 'gridPanGestureRecognized' that is not exposed to Objective-C

Add '@objc' to expose this instance method to Objective-C
```
```
Argument of '#selector' refers to instance method 'timerTriggered()' that is not exposed to Objective-C

Add '@objc' to expose this instance method to Objective-C
```

## Issue Type (Can be multiple)
[x] Build - Can’t install or import the SDK
[ ] Performance - Performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Other (Specify)

## Steps to reproduce

The project is open source: https://github.com/capawesome-team/capacitor-cloudinary/tree/main/ios
You can just try to build the project.

## Error screenshots or Stack Trace (if applicable)

![grafik](https://user-images.githubusercontent.com/13857929/203831226-44b98f44-7b22-4770-a2d5-88eddb846c01.png)

## Build/Dependency management
[x] Cocoa-Pods
[ ] Carthage
[ ] Manual import
[ ] Other (Specify)

## Is the issue reproducible only on a specific device?
[x] No
[ ] Yes (specify model + iOS version)

## Versions and Libraries (fill in the version numbers)
iOS Cloudinary SDK version - 3.3.0
OSX (on the dev environment) - 12.6
XCode - 14.1
Swift - 5.1
Target iOS - 13.0

**Comment by michalkcloudinay** [comment]
Hi @robingenz,

I see you opened a direct ticket to our support team, we will further discuss this on that thread.

Thanks

**Comment by robingenz** [comment]
Hi @michalkcloudinay,
thank you for your response.
It would be great if we could discuss this here so that it is transparent to the open source community. I know a few people in the Capacitor community are following this issue.

Regarding your mail: I am aware that this is a native SDK. How this SDK is then called from the WebView is handled by Capacitor. We can ignore that for now. I only mentioned Capacitor to give some context. However, this requires that I can convert my Swift class to Objective-C and that's not working right now.

According to Cloudinary documentation this should be supported though, see:
![grafik](https://user-images.githubusercontent.com/13857929/204287179-9bde5050-6a9b-4e63-b199-1e78e507c2c3.png)
and 
![grafik](https://user-images.githubusercontent.com/13857929/204287753-66eee74d-5091-439a-a8d4-c883f36dcbf6.png)

**Comment by michalkcloudinay** [comment]
Hi @robingenz,
Sure, we can continue the discussion here. 
We are further checking this internally and I will update here once I have new insights. 
Thanks

**Comment by robingenz** [comment]
Hi @michalkcloudinay,
Capacitor is just another SDK (pod) in the XCode project and has no influence on the build process. I use normal `@objc` attributes (read more [here](https://www.hackingwithswift.com/example-code/language/what-is-the-objc-attribute)) that tell XCode to export the Code not only as Swift code but also as Objective-C code. It seems that only certain parts of the Cloudinary SDK are affected where this is lacking compatibility. 

Please use my provided example for testing so you can reproduce the issue:

```
$ git clone https://github.com/capawesome-team/capacitor-cloudinary.git
$ npm install
$ cd ios
$ pod install
$ open Plugin.xcworkspace
```

Now when you build the project in Xcode, you get the build error.

**Comment by atdcloud** [comment]
Hi @robingenz, 
I followed the steps but I was able to build the project successfully: https://tdatu-res.cloudinary.com/video/upload/v1669753413/ios/ciggqzvexocie3s2ljrp.mp4

Perhaps re-clone the repo again, redo the steps but add `npm install | tee -a install-steps.log` and `pod install | tee -a ../install-steps.log`?  This should save the normal output in install-steps.log file where we can check if any of the depencies were properly installed. 

Regards, 
Anthony

**Comment by robingenz** [comment]
@atdcloud Thank you for your help!
It was actually a local problem. After running the following it worked:
```
pod cache clean 'Cloudinary' --all
pod install
```
Unfortunately, I don't know how this could happen, since I installed the Cloudinary pod for the first time with version 3.3.0.
Either way, thanks to you both for your help!

**Comment by atdcloud** [comment]
@robingenz Thanks for the update and sharing your solutions here! Glad everything is OK now.
