### ISSUE TITLE
Return `bytes` property

### ISSUE THREAD

**Issue by robingenz** [cloudinary/cloudinary_ios#399]
## Explain your use case

We would like to display various meta-information (including `bytes`) to the user after the upload.

## Describe the problem you’re trying to solve

I need access to the `bytes` property, which is already available via Rest API after an upload (see [Sample Response](https://cloudinary.com/documentation/image_upload_api_reference#rename_response)):

```json
{
  ...
  "bytes": 1414789,
  ...
}
```

You can also access this property via the Cloudinary Android SDK. 
**Only the Cloudinary iOS SDK does not seem to provide this property.**
![grafik](https://user-images.githubusercontent.com/13857929/226174882-0c60ed19-b793-4988-aebf-5ef63a6f20d2.png)

## Do you have a proposed solution?

Yes, expose the `bytes` property.

--------

Related to https://github.com/capawesome-team/capacitor-plugins/issues/5

**Comment by adimiz1** [comment]
The attributes exist but under a different name.
The outcome of an upload is a `CLDUploadResult`, the attribute for bytes is called `length`
So to get it you'll need to use:
`result.length`
