### ISSUE TITLE
Cloudinary bitcode warnings

### ISSUE THREAD

**Issue by natanavra** [cloudinary/cloudinary_ios#40]
`ld: bitcode bundle could not be generated because '/path/to/project/libCloudinary.a(CLTransformation.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7`

and 

`ld: bitcode bundle could not be generated because '/path/to/project/libCloudinary.a(CLTransformation.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64`

Disabling bitcode gives me a ton of warnings (138) of these types:
`warning: Could not resolve external type c:objc(cs)NSString`
`warning: /var/folders/gg/_ybj23096kd8b8qb5lmbl6mr0000gn/C/com.apple.DeveloperTools/7.2.1-7C1002/Xcode/SharedPrecompiledHeaders/Cloudinary-Prefix-bgqfpmstnmfqfohfifuzqiqlsfbe/Cloudinary-Prefix.pch.pch: No such file or directory`

**Comment by Marindrew** [comment]
I have similar issue:

ld: '/Users/path/to/project/libCloudinary.a(CLCloudinary.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

**Comment by mrchristopher124** [comment]
Bump. Any update on full bitcode support? :)

**Comment by robinsmedberg** [comment]
Bump. Any update on full bitcode support? :)

**Comment by mrchristopher124** [comment]
Bump. Any update on full bitcode support? :)

**Comment by kukat** [comment]
Bump. Any update on full bitcode support? :)

**Comment by tocker** [comment]
Hi @kukat,

We are commend working on a new code for this library. We will release bit code support with it.

**Comment by ou2s** [comment]
Bump. Any update on full bitcode support? :)

**Comment by zhuohongwei** [comment]
@tocker Any update on full bitcode support?

**Comment by v-ken** [comment]
@tocker Any update on the new code?

**Comment by engineermanas** [comment]
@tocker : Is there any update on full BitCode Enable Support

**Comment by ou2s** [comment]
@tocker could you give us an update please?

**Comment by taragano** [comment]
I'm very sorry for the long delay,
We are working on releasing a new major version of the library.
While there isn't a specific ETA for this yet, we'll be happy to let you know of any updates.

**Comment by roeeba** [comment]
The library was updated several times since the last comment. This issue should be resolved by now. Please let us know if that's not the case. Closing.
