### ISSUE TITLE
Cannot find 'UIDevice' in scope -> in CLDAnalytics

### ISSUE THREAD

**Issue by MinaMaherR** [cloudinary/cloudinary_ios#410]
## Bug report for Cloudinary iOS SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two.
… cannot build the app after installing cloudinary, 
within CLDAnalytics i got error states that "Cannot find 'UIDevice' in scope" and needs to import UIKit 
Xcode version: 14.2
Coudinary version: 4.1.0

## Issue Type (Can be multiple)
[x] Build - Can’t install or import the SDK
[ ] Performance - Performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Other (Specify)

## Steps to reproduce
import Coudinary and build

## Error screenshots or Stack Trace (if applicable)
…
<img width="1159" alt="Error Screenshot" src="https://github.com/cloudinary/cloudinary_ios/assets/20876050/3c15486b-5752-4b5e-bf44-2a97290a2c0d">

## Build/Dependency management
[ ] Cocoa-Pods
[ ] Carthage
[ ] Manual import
[x] Other (SPM: swift package manager)

## Is the issue reproducible only on a specific device?
[x] No
[ ] Yes (specify model + iOS version)

## Versions and Libraries (fill in the version numbers)
iOS Cloudinary SDK version - 4.1.0

Repository
If possible, please provide a link to a reproducible repository that showcases the problem

**Comment by adimiz1** [comment]
The issue was solved, please update to the latest version
