### ISSUE TITLE
{"error": "Stale request - reported time is 2023-12-19 23:07:41 +0000 which is more than 1 hour ago"}

### ISSUE THREAD

**Issue by AbdoRabie11** [cloudinary/cloudinary_ios#417]
it gives me this error when i am trying to upload media file on my react native app and am using node js on the back end and cloudinary , and the time on the machine is correct

**Comment by dannyv-cloudinary** [comment]
Hey @AbdoRabie11 .

It seems this issue is regarding our React Native SDK, rather than the iOS one. Could you please raise this over in https://github.com/cloudinary/cloudinary-react-native and provide a code sample and reproduction steps?

Many thanks.
