### ISSUE TITLE
Support App Privacy Manifest

### ISSUE THREAD

**Issue by toya108** [cloudinary/cloudinary_ios#418]
## Feature request for Cloudinary iOS SDK
Hi!
Is there a plan to include the `PrivacyInfo.xcprivacy` manifest as required by Apple?
ref: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

Since `cloudinary_ios` is using  [modificationDate](https://developer.apple.com/documentation/foundation/fileattributekey/1410058-modificationdate) and [contentModificationDateKey](https://developer.apple.com/documentation/foundation/urlresourcekey/1408803-contentmodificationdatekey), this SDK needs to declare that its use of File timestamp APIs.

## Explain your use case
I would like to reduce the risk of being rejected in the store review process by using an SDK that is compatible with the privacy manifest.

## Describe the problem you’re trying to solve
the same as the above

## Do you have a proposed solution?
Yes. If possible, I will create a PR for adding PrivacyInfo.

**Comment by Vdeub-cloudinary** [comment]
Hi @toya108, you should be able to create a PR and our development team can review it. Thanks for contributing

**Comment by Vdeub-cloudinary** [comment]
@toya108, thanks for your contribution with this PR. 
Due to the sensitivity of this subject, the dev team will take it internally with our security team to make sure nothing is missed.
