### ISSUE TITLE
andProgress block never called

### ISSUE THREAD

**Issue by holgersindbaek** [cloudinary/cloudinary_ios#42]
I'm letting people upload a new avatar and it's working fine, except my "andProgress" block is never called, so I can't show people an indicator of how far they are.

Why wouldn't "andProgress" be called? I'm testing in the simulator if that helps.

**Comment by nadavofi** [comment]
Would it be possible for you to share some code snippets so we can have a deeper look?
If privacy is an issue then you can do that privately via a support ticket.

**Comment by nadavofi** [comment]
We're closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact [our support](http://support.cloudinary.com) or create a new ticket if you have any additional issues.
