### ISSUE TITLE
Version 2.5.0 does not compile

### ISSUE THREAD

**Issue by dmi3j** [cloudinary/cloudinary_ios#424]
Installed version 4.5.0 via CocoaPods. Version does not compile. 

Plenty of issues. First one in CLDVideoPlayer.swift
`/Users/xxx/Pods/Cloudinary/Cloudinary/Classes/ios/Video/CLDVideoPlayer.swift:42:25 Cannot find type 'VideoEventsManager' in scope
`

<img width="349" alt="Screenshot 2024-02-27 at 09 38 01" src="https://github.com/cloudinary/cloudinary_ios/assets/120496/949f3933-20f0-4fb2-9620-c22110dbd79a">

iOS Cloudinary SDK version - 4.5.0.
XCode - 15.2
Target iOS - 16.0

**Comment by adimiz1** [comment]
Hello @dmi3j , thank you for reporting the issue
Version 2.5.0 did not have the CLDVideoPlayer implemented in it. Do you refer to 4.5.0?
We are investigating the issue, please use version 4.2.0 till then.

**Comment by dmi3j** [comment]
My fault. 4.5.0 is the version.

**Comment by atdcloud** [comment]
Hi @dmi3j 
I was able to test the CLDVideoPlayer playback without any issues. 

Podfile: 

```
platform :ios, '15.2'

target 'CLDVidPlayer2' do
  pod 'Cloudinary', '~> 4.5.0'
end
```

Xcode 15.2

Screen recording: 
https://github.com/cloudinary/cloudinary_ios/assets/91624228/5c360900-a291-4914-976c-16f8631299bc


```
import SwiftUI
import Cloudinary
import AVKit


let config = CLDConfiguration(cloudName: "<cloud_name>", secure: true)
let cld = CLDCloudinary(configuration: config)

struct ContentView: View {
    ...

                VideoPlayer(player: CLDVideoPlayer(publicId: "<public_id>", cloudinary: cld))
                .frame(width: 500, height: 250)

```

I hope that helps.

**Comment by atdcloud** [comment]
Hi @dmi3j, 

I see.  I tried to issue a `pod install` and it feels like fetching Spec.git stalls.  For now, I omitted the `source 'https://github.com/CocoaPods/Specs.git'` and pod installation went without any issues.  Ultimately, this is what I got: 

```
platform :ios, '16.0'
project 'CloudinaryDemo.xcodeproj'
workspace 'CloudinaryDemo'

target 'CloudinaryDemo' do
  pod 'Cloudinary', '4.5.0'
end 

use_frameworks!
inhibit_all_warnings!
```

Can you give that a try and let me know how it goes?

**Comment by atdcloud** [comment]
Hi @dmi3j , 

Did you manage to compile?

**Comment by dmi3j** [comment]
I can confirm version 4.7.0 works fine for me.
