### ISSUE TITLE
Randomly crashing when upload image

### ISSUE THREAD

**Issue by levantAJ** [cloudinary/cloudinary_ios#44]
<img width="1048" alt="screen shot 2016-04-29 at 1 06 17 pm" src="https://cloud.githubusercontent.com/assets/6329656/14909234/3c3393a6-0e0b-11e6-8045-6da77f9e1662.png">
I wrote by Swift2.2 and upload image using: 

```
func upload(file: AnyObject!, options: [NSObject : AnyObject]!, withCompletion completionBlock: CLUploaderCompletion!, andProgress progressBlock: CLUploaderProgress!)
```

I have handled the `progressBlock`, but sometime it's success, sometime not. Anybody know the reason, please help me, thanks

**Comment by timbroder** [comment]
I'm running into this as well

**Comment by timbroder** [comment]
@levantAJ using it like this has avoided that issue for me

```swift
uploader.upload(file, options: nil,
            withCompletion: { (dataDictionary: [NSObject: AnyObject]!, errorResult:String!, code:Int, context: AnyObject!) -> Void in
                if errorResult != nil {
                   
                } else {
                   
                }
            },
            andProgress: { (bytesWritten:Int, totalBytesWritten:Int, totalBytesExpectedToWrite:Int, context:AnyObject!) -> Void in
                print("Upload progress: \((totalBytesWritten * 100)/totalBytesExpectedToWrite) %")
            }
        )
```

**Comment by tocker** [comment]
@levantAJ and @timbroder - is this still an issue?

**Comment by timbroder** [comment]
@tocker not for us, I've been able to work around it

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
