### ISSUE TITLE
Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found

### ISSUE THREAD

**Issue by khoogheem** [cloudinary/cloudinary_ios#440]
Using the current pod I am starting to see this after updating to cocoa pods 1.16.0 (right now I can't go back due to home-brew).
on Xcode 16 and 16.1

I am seeing this issue

```
ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
ld: warning: Could not parse or use implicit file '/Applications/Xcode_16.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/SwiftUICore.framework/SwiftUICore.tbd': cannot link directly with 'SwiftUICore' because product being built is not an allowed client of it
Undefined symbols for architecture arm64:
  "Cloudinary.CLDExpression.__allocating_init(expressionKey: Cloudinary.CLDExpression.ExpressionKeys) -> Cloudinary.CLDExpression", referenced from:
      full type metadata for Cloudinary.CLDConditionExpression in CLDConditionExpression.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by tamaracloudinary** [comment]
Hi @khoogheem this doesn't seem to be related to Cloudinary, but can you please share your code?

**Comment by dmi3j** [comment]
This issue is caused by Cocoapods 1.16.1. Apparently some misconfiguration in project file leads to this error. Still investigating mine issues.

**Comment by khoogheem** [comment]
That is what it seems.. as 1.13 pod make it not show up..
Also odd that it picks up on `CoreAudioTypes` which doesn't seem to be even used?

**Comment by dmi3j** [comment]
Fixed mine project by moving "Cloudinary" from pods file to SPM. 🤷‍♂️

**Comment by tamaracloudinary** [comment]
@khoogheem are you still having issues?

**Comment by khoogheem** [comment]
@tamaracloudinary I am cool with just closing this and saying its all a Cocoapod issue
