### ISSUE TITLE
Q: Resuming image uploads (due to suspending app)

### ISSUE THREAD

**Issue by willks** [cloudinary/cloudinary_ios#48]
We've kind of hit a snag during development of an iOS app. Turns out that if a user backgrounds their app (that is, hits the home button) - all tasks are suspended mid-way, which breaks up the upload process and is not always recoverable (only less than a minute or two based on my rough tests).
As we can't force users to keep the app open during the upload process (because they could have, say 100 images - and a spotty connection) - is there "Cloudinary" advised way to tackle this issue? We've thought about implementing our own upload mechanism to support this (based on bytes uploaded, total byte counts etc etc, to AWS S3 and using custom attributes - and using the Cloudinary S3 integration) but it seems a massive round-about way to implement something that is fairly trivial in the file sharing world. 
Of course, this would only work for users that opt for using their own filenames. We've already worked out (by modifying this projects source) how to get simultaneous file uploads with reporting for each dispatched image (using react-native), but resuming interrupted uploads seems to be a sticking point for our app.

Dropbox currently supports this with their custom app (see https://www.dropbox.com/en/help/209). Obviously a different use-case, but the customer benefits would be in saving upload data usage and easier integration for your customers (and more subscribers for you!!)

Any advise would be appreciated.

**Comment by willks** [comment]
Here's an error I caught while trying to test the scenario - approximately 9 minutes pause (which is a real world scenario):

2016-08-18 22:39:09.134 BLahApp[2571:738139] Expected: 1941487 | Total Written: 524288


2016-08-18 22:39:12.545 BLahApp[2571:738139] ► SUSPEND (enabled? 0)
2016-08-18 22:44:53.221 BLahApp[2571:738139] ► RESUME
2016-08-18 22:44:53.239 [info][tid:com.facebook.react.JavaScript] 'Error while uploading imgage, image placed back on queue for upload', { [Error: Fail]
  line: 59,
  column: 216,
  sourceURL: 'file:///var/containers/Bundle/Application/635A1670-5CEB-4C93-92D9-A0A4AF63E657/BlahApp.app/main.jsbundle',
  framesToPop: 1,
  code: '0',
  nativeStackIOS: 
   [ '0   BLahApp                            0x00000001001e3234 RCTJSErrorFromCodeMessageAndNSError + 92',
     '1   BLahApp                            0x00000001001b3e78 __41-[RCTModuleMethod processMethodSignature]_block_invoke_2.213 + 92',
     '2   BLahApp                            0x00000001000ae1c8 -[RNCloudinaryCallbackDelegate uploaderError:code:context:] + 464',
     '3   Cloudinary                          0x0000000100ef5f0c -[CLUploader error:code:] + 160',
     '4   Cloudinary                          0x0000000100ef3660 -[CLUploader connection:didFailWithError:] + 332',
     '5   CFNetwork                           0x000000018382d6a0 <redacted> + 80',
     '6   CFNetwork                           0x000000018382d630 <redacted> + 200',
     '7   CFNetwork                           0x000000018382d7f0 <redacted> + 56',
     '8   CFNetwork                           0x0000000183801088 <redacted> + 80',
     '9   CFNetwork                           0x000000018378939c <redacted> + 116',
     '10  CFNetwork                           0x000000018378741c <redacted> + 108',
     '11  libdispatch.dylib                   0x00000001023eda3c _dispatch_client_callout + 16',
     '12  libdispatch.dylib                   0x00000001023f71e0 _dispatch_block_invoke + 564',
     '13  CFNetwork                           0x000000018367fac0 <redacted> + 36',
     '14  CoreFoundation                      0x0000000182f9067c CFArrayApplyFunction + 68',
     '15  CFNetwork                           0x000000018367f9a4 <redacted> + 136',
     '16  CFNetwork                           0x000000018367f864 <redacted> + 312',
     '17  CFNetwork                           0x000000018367f690 <redacted> + 68',
     '18  CoreFoundation                      0x000000018306909c <redacted> + 24',
     '19  CoreFoundation                      0x0000000183068ab0 <redacted> + 412',
     '20  CoreFoundation                      0x0000000183066830 <redacted> + 724',
     '21  CoreFoundation                      0x0000000182f90c50 CFRunLoopRunSpecific + 384',
     '22  GraphicsServices                    0x0000000184878088 GSEventRunModal + 180',
     '23  UIKit                               0x000000018827a088 UIApplicationMain + 204',
     '24  BlahApp                             0x00000001000adcfc main + 88',
     '25  libdyld.dylib                       0x0000000182b2e8b8 <redacted> + 4' ],
  domain: 'Upload failure' }


This leads me to another question relating to my OP - is "NSURLSession" being used for uploads?

**Comment by willks** [comment]
I haven't completely solved this, but I have mitigated the issues. I stopped using the Cloudinary library for iOS and started using Alamofire do the work (with a background manager). My uploads complete now without being stopped when a user backgrounds their app. Still early day, and still doesn't solve the issue when a user's internet drops out but, better than before!

Going to close this.

**Comment by taragano** [comment]
I'm sorry @willks, note that there is a major new version coming soon that will utilize AlamoFire internally.

**Comment by willks** [comment]
@taragano Hey that sounds great! I'd love not using my hand-rolled code (specially since I'm a green DEV @ Swift/Objc!). For the meantime it's behaving but I'd rather use something official, when it's out.

Thanks
