### ISSUE TITLE
URL composer should return secure url

### ISSUE THREAD

**Issue by oferRounds** [cloudinary/cloudinary_ios#50]
Cloudinary's methods: `url:` and `url:options:` returns `http` URL instead of `https`.

**Comment by taragano** [comment]
Hi @oferRounds,
To generate HTTPS URLs, you should also pass the `secure` parameter.
Here's a reference:
https://github.com/cloudinary/cloudinary_ios/blob/5e192f91360e6d9ac13937fe09dd0c8ffbe72eee/CloudinaryTests/CloudinaryTests.m#L58-L62

**Comment by oferRounds** [comment]
@taragano - thanks! I wasn't aware of this option, works great. Thanks again
