### ISSUE TITLE
'Expected NSString or NSNumber' Error

### ISSUE THREAD

**Issue by valtambok** [cloudinary/cloudinary_ios#53]
Whenever I set Cloudinary's "signature", "timestamp", and "api_key", I get this error: 
`*** Terminating app due to uncaught exception 'CloudinaryError', reason: 'Expected NSString or NSNumber'`
My CLUploader is somewhat structured like this:

``` objective-c
[uploader upload:imageData options:@{@"signature" : responseData[kCLOUDINARY_SIGNATURE],
                                                 @"timestamp" : responseData[kCLOUDINARY_TIMESTAMP],
                                                 @"api_key" : responseData[kCLOUDINARY_API_KEY],
                                                 kTAGS : imageTags,
                                                 kRESOURCE_TYPE : kRESOURCE_TYPE_IMAGE,
                                                 kFORMAT : kFORMAT_JPG, 
                                                 kTRANSFORMATION : imageTransformation
                                                 }];
```

**Comment by nadavofi** [comment]
Hi, can you share more information regarding the source of `responseData` and the types it delivers? Maybe try eliminating by hard-coding some `signature`, `timestamp` and `api_key` values and see which one fails on a type issue.
