### ISSUE TITLE
How to delete a single image or video.

### ISSUE THREAD

**Issue by dineshguptha** [cloudinary/cloudinary_ios#55]
I want to delete a single image or video and how can I implement from app side.

**Comment by MaorGariv** [comment]
You can use the [destroy](https://github.com/cloudinary/cloudinary_ios/blob/master/Cloudinary/CLUploader.m#L122) method. The `resource_type` is `image` by default. To delete a video, simply set the `resource_type` to `video`.
For more information - 
http://cloudinary.com/documentation/image_upload_api_reference#destroy

**Comment by MaorGariv** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
