### ISSUE TITLE
Cloudinary will not build

### ISSUE THREAD

**Issue by darkmantle** [cloudinary/cloudinary_ios#57]
I am using CocoaPods, setup exactly how suggested in the documentation, but 2 things happen.

First it requires 9.0 platform (docs say 8.0) and secondly whenever building it says "No such module CLDCrypto" despite the module actually being within the code.

**Comment by tocker** [comment]
Hi @darkmantle,
Thanks for trying the new code!
The CLDCrypto module was supposed to be created during the installation of the pod.
We're investigating this issue.

**Comment by tocker** [comment]
Can you please verify that the following path exists under the root of your project?

```
Pods/Cloudinary/Cloudinary/Frameworks/CLDCrypto/
```

If it does, please try changing the Framework search path from `./Cloudinary/Frameworks/CLDCrypto/` to `./Cloudinary/Cloudinary/Frameworks/CLDCrypto/` (see photo below). If this works, I'll modify the build script accordingly.

![image](https://cloud.githubusercontent.com/assets/346642/22149864/c12ff1d2-df1e-11e6-9706-68f92f885ce8.png)

**Comment by meandkareem** [comment]
I have same issue .. where should I change this path ? this is generated via cocapods $inherited so I cant change it in Xcode

**Comment by darkmantle** [comment]
Changing that fixed it - it now builds without an issue.

Thanks!

**Comment by darkmantle** [comment]
Sorry, it **did** work, i just edited the wrong build settings! 

As of right now I can build and use the app, with Cloudinary imported.

Cheers.

**Comment by darkmantle** [comment]
However now there are warnings saying "Directory not found for option '-FCloudinary/Cloudinary/Frameworks/CLDCrypto/iphoneos'" which is annoying. Does not stop the app working but just so you know!

**Comment by chrisellsworth** [comment]
Those who don't have `Pods/` in source control might find something like the following addition to `Podfile` to be useful:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # remove this when https://github.com/cloudinary/cloudinary_ios/issues/57 is resolved
      if target.name == 'Cloudinary'
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] = [
          '$(inherited)',
          './Cloudinary/Cloudinary/Frameworks/CLDCrypto/$(PLATFORM_NAME)',
          '$PODS_CONFIGURATION_BUILD_DIR/Alamofire'
        ]
      end
    end
  end
end
```

**Comment by darkmantle** [comment]
@chrisellsworth Worked perfect for me

**Comment by tocker** [comment]
Hi All,

The issue was in the way `pod lib lint` works vs. `pod install`.
Please try version 2.0.1. It should build correctly 🙏 .
You will get the following linker warning which you can safely ignore:

```
ld: warning: directory not found for option '-FCloudinary/Frameworks/CLDCrypto/iphonesimulator'
```

Please let us know if this solved you issue!

**Comment by chrisellsworth** [comment]
It builds! Thanks @tocker!

**Comment by wouterBouwmeester** [comment]
I have kind of the same issue:

I am able to build to any device, but when I try to Archive I get:
ld: warning: directory not found for option '-FCloudinary/Frameworks/CLDCrypto/iphoneos'
ld: framework not found Pods_Campground_App
clang: error: linker command failed with exit code 1 (use -v to see invocation)

This causes the Archive to fail.

I tried to fix this by updating to 2.0.1, but after updating the error changes to:
ld: warning: directory not found for option '-FCloudinary/Cloudinary/Frameworks/CLDCrypto/iphoneos'
ld: framework not found Pods_Campground_App
clang: error: linker command failed with exit code 1 (use -v to see invocation)

The Framework search path was wrong after the update so I changed it to: "./Cloudinary/Cloudinary/Frameworks/CLDCrypto/$(PLATFORM_NAME)"

but then the error got back to:
ld: warning: directory not found for option '-FCloudinary/Frameworks/CLDCrypto/iphoneos'
ld: framework not found Pods_Campground_App
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I noticed that the xcconfig files still had Cloudinary/Frameworks, but even after those to Cloudinary/Cloudinary/Frameworks I still get the same error.

I searched all files in my project for "Cloudinary/Framework" and noticed that it occurs in UserInterfaceState.xcuserstate, but when i delete this file Xcode generates a new file with the same wrong path.

So I'm kind of stuck.

Is there anything I can try to get around this issue and archive my project again?

**Comment by paulhimes** [comment]
Version 2.0.1 is still putting a duplicate reference to the wrong directory in the **Framework Search Paths** and the **Import Paths**: 

$(PODS_ROOT)/Cloudinary/Cloudinary/Frameworks/CLDCrypto/$(PLATFORM_NAME)
./Cloudinary/Frameworks/CLDCrypto/$(PLATFORM_NAME)

**Comment by roeeba** [comment]
Hi @paulhimes. I apologise for the delayed reply. While I'm not sure it's still relevant to you, some CLDCrypto issues were solved in 2.0.2 so this may already be fixed. That said, please let us know if you're still seeing an issue, and we'll gladly help further.

**Comment by marcospolanco** [comment]
This is still broken in 2.0.2. I had to change the '11.0.sdk' to '11.1.sdk' to make it work. ![screen shot 2017-11-10 at 8 16 07 am](https://user-images.githubusercontent.com/179455/32667396-75479c6c-c5ef-11e7-81bd-243e97b692a4.png)

**Comment by roeeba** [comment]
Hi @marcospolanco, please refer to the following thread for possible workarounds - https://github.com/cloudinary/cloudinary_ios/issues/107

And to this comment in particular - 
https://github.com/cloudinary/cloudinary_ios/issues/107#issuecomment-331698257

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
