### ISSUE TITLE
Swift 3 configuration

### ISSUE THREAD

**Issue by darkmantle** [cloudinary/cloudinary_ios#58]
Since the document has not been updated it is hard to figure out exactly how to configure Cloudinary for use with Swift 3.0

Specifically it cannot resolve CLDConfiguration and CLCloudinary has url option instead of config option.

**Comment by darkmantle** [comment]
On top of that I cannot even generate an URL as that has also been changed. Can we get some documentation available ASAP please? Or at least instructions on how to both generate URL and upload images. Without these my app development has to be paused!

**Comment by nadavofi** [comment]
Hi David,
While we didn't want to stall our users from getting Swift 3.0 support, we're aware of the need in detailed documentation and are working to get this done as quick as possible.
Meantime, for such tasks you can either have a look at the included [Sample project](https://github.com/cloudinary/cloudinary_ios/tree/master/Samples/PhotoAlbumApp) or [tests](https://github.com/cloudinary/cloudinary_ios/tree/master/CloudinaryTests). If you're still missing any specific functionality, please don't hesitate to elaborate and we'll be happy to share some additional code snippets here or [via a support ticket](https://support.cloudinary.com/hc/en-us/requests/new).

**Comment by thanhhung071** [comment]
Hi Nadavofi,
On Swift 3.0. When i uploading a video/image and waiting for complete, i want to cancel this process. But i didn't find in document. Can we cancel this process ?

**Comment by shirlymanor** [comment]
Hi David,

Canceling is possible but there are some limitations.

When starting an upload (download too, for that matter) you can keep the request object:

let request = cloudinary.createUploader().signedUpload(url: file, params: params)

(This can work after chaining more options to the request, if needed).

The request instance has a cancel() function - calling it cancels the request. There's one caveat though - The server won't necessarily know you tried to cancel. A 'ghost' resource may remain in your media library. The client won't really know it's there as it didn't get a proper response with public_id (and thus has no way to access it), but it will be there - ListResource API and the media library UI will show it. 
This can happen if canceling was a bit too late and the resource is already uploaded, and in some cases even if it stopped in the middle (e.g. a partial video file).

**Comment by shirlymanor** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Comment by bniranjan** [comment]
I am getting a error: Error Domain=com.cloudinary.error Code=400 "(null)" UserInfo={message=Upload preset not found}. I am using cloudinary 2.8
