### ISSUE TITLE
No such module 'CLDCrypto'

### ISSUE THREAD

**Issue by levantAJ** [cloudinary/cloudinary_ios#60]
I'm using `cocoapods-1.2.0.rc.1`, and using Cloudinary 2.0.0, after run `pod install`, XCode throw error:  
`No such module 'CLDCrypto'` at `import CLDCrypto`
Please help me to give a solution? thx team

**Comment by tocker** [comment]
Duplicate of #57. See #57 for an intermediate solution while we work to solve the issue.
