### ISSUE TITLE
support for downloading videos with cache

### ISSUE THREAD

**Issue by Nautiyalsachin** [cloudinary/cloudinary_ios#62]
I checked your repo and there is a class named CLDDownloader which provide support for downloading images (in  fetchImage: method). Can you also add a method or tell me an easy way to fetch a remote video from specific URL asynchronously.

**Comment by tocker** [comment]
We do not support downloading and caching videos but you can accomplish it using Alamofire.
In the following example we download our famous [dog video](https://res.cloudinary.com/demo/video/upload/dog) as QuickTime ("mov") and print the path of the downloaded file and its size:

```swift
    func DownloadVideo() {
        let destination: DownloadRequest.DownloadFileDestination = { _, _ in
            let documentsURL: URL = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
            let fileURL : URL = documentsURL.appendingPathComponent("dog.mov")

            return (fileURL, [.removePreviousFile, .createIntermediateDirectories])
        }
        let config = CLDConfiguration(cloudName: "demo")
        let cloudinary = CLDCloudinary(configuration: config)
        let urlString = cloudinary.createUrl().setResourceType(.video).generate("dog.mov")!
        Alamofire.download(urlString, to: destination).response { response in
            print("Got response: \(response)")
            if response.error == nil, let imagePath = response.destinationURL?.path {
                print("Video path: \(imagePath)")
                var fileSize : UInt64
                do {
                    let attr = try FileManager.default.attributesOfItem(atPath: imagePath)
                    fileSize = attr[FileAttributeKey.size] as! UInt64
                    print("Video size: \(fileSize)")
                } catch {
                    print("Error: \(error)")
                }
            }
        }
    }
```

I hope this helps!

**Comment by Nautiyalsachin** [comment]
I wanted some auto handled caching videos thing but this will help, Thanks for the reply.

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
