### ISSUE TITLE
Docs for fetching remote images on iOS

### ISSUE THREAD

**Issue by Shivam101** [cloudinary/cloudinary_ios#63]
Hello,
I am looking to convert my existing code logic to be compatible with the recent SDK update. 
I have understood most aspects of it, however, I am unsure of how image fetching using `createUrl()` can be done in case of fetch(using a remote url) and upload(using an image id)

Here is what I have implemented - 

```    

    if (downloadType == DownloadType.Fetch) {
            if let url = (cloudinary?.createUrl().
setType(CLDType.fetch).
setTransformation(transformation).
generate(source)) {
                transformedImageUrl = url
            }
        }
        else {
            if let url = (cloudinary?.createUrl().
setType(CLDType.upload).
setTransformation(transformation).
generate(source)) {
                transformedImageUrl = url
            }
        }

```

My source in case of `fetch` would be a remote image url and in case of `upload` would be an image id. But I always get a nil url value. 
What am I doing wrong here? 

Thanks!

**Comment by roeeba** [comment]
Hi, @Shivam101. I see that you've already been answered back then via a support ticket. I'm safely closing this one, but feel free to reopen it or open a new ticket if you still have any questions.
