### ISSUE TITLE
URL Generation Broken (Decimal Numbers)

### ISSUE THREAD

**Issue by Jiropole** [cloudinary/cloudinary_ios#64]
I just tried to migrate from 1.x, but it appears that url generation is broken in 2.x. The resulting urls have decimal places in numbers, which causes the server to respond with 400 errors. e.g.:
```
https://res.cloudinary.com/<app_id>/image/upload/c_fit,f_auto,h_562.0,q_auto,w_562.0/<public_id>
```

If I do a side-by-side with the output from the old version, this is the only difference. I haven't changed anything other than migrating to the new SDK. Example of updated transform generation code:
```
let xform = CLDTransformation()
xform.setWidth(Float(size.width * screenScale))
xform.setHeight(Float(size.height * screenScale))
```

Updated url generation code:
```
if let urlString = cloudinary.createUrl().setTransformation(xform).setType(access.rawValue).generate(identifier) {
    return URL(string: urlString)
}
return nil
```

**Comment by nadavofi** [comment]
Functions `setWidth` and `setHeight` are overloaded to support both Int and Float as input values. Note that Float values are used to indicate a relative resizing (e.g. `w_0.5` for half the width of the input image).
This may have not yet been supported on the outdated (1.x) SDK version. I think it would be best if you switched from Float to Int representations in your code.

**Comment by Jiropole** [comment]
I see. I can do that as a workaround, however I would think it would add robustness if the library were to simply round any incoming float values when used in integer-only context, as when specifying pixel dimensions. Especially since the iOS convention is to specify dimensions as floats, so without handling that properly in the library you rely on the user to remember to convert to a less conventional data type.

Thanks!

**Comment by nadavofi** [comment]
> round any incoming float values when used in integer-only context

Can you please share a concrete example to clarify your intention? Note that for this purpose, float numbers must remain a valid dimension value.

**Comment by Jiropole** [comment]
Sure, I just mean if I do pass in float values to e.g. `CLTransformation().width`, it would make sense that when the outgoing URL is prepared, those are automatically formatted as an integer string, regardless of the type of value passed in. This makes the system tolerant of various types and ensure valid urls are produced.

**Comment by MaorGariv** [comment]
Hi @Jiropole,

I might be missing something here, but what about relative values for width that require float values (e.g., half the original width - w_0.5)?

**Comment by Jiropole** [comment]
Thanks @MaorGariv. Good question, I haven't touched the project for some time. Will get back to you as soon as I can.

**Comment by YuriiTrach** [comment]
setDprAuto doesn't work as well. I have to do setDpr("\(Int(UIScreen.main.scale))") to workaround this

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
