### ISSUE TITLE
Error on video uploading

### ISSUE THREAD

**Issue by ilia-dev** [cloudinary/cloudinary_ios#65]
I use this code:
```
let params: [String: AnyObject] = [
    "signature": request.signature as NSString,
    "public_id": request.publicId as NSString,
    "timestamp": request.timestamp.description as NSString,
    "api_key": request.apiKey  as NSString,
    "resource_type": "video" as NSString
]
cloudinary.createUploader().upload(url: videoUrl, uploadPreset: "", params: params, progress: nil) { (result, error) in (result, error) in
    // ...
}
```

`videoUrl ` here  is URL of video which was exported from the Media Library and placed in app sandbox.

But I am getting the next error when try to upload video: `Invalid image file`

What am I doing wrong?

**Comment by abanet** [comment]
It happend the same to me and at the end  the problem was in the videoUrl:
```
guard let path = Bundle.main.path(forResource: "diego", ofType:"MOV") else {
        debugPrint("video not found")
        return
    }
```
I got "video not found" but the name of the video was ok.

I fixed this problem going to the target->Build Phases->Copy Bundle Resource and adding the video file to the list of resources.

**Comment by ilia-dev** [comment]
I get the same error when using method
`cloudinary.createUploader().upload(data: data, uploadPreset: "", params: params, progress: nil) { ... }`
Here I successfully read file content in advance, so the problem is not related to permission or file absence.

Also, I tried to set 
`"resource_type": "raw"`
But the error was the same. It looks like `resource_type ` value is ignored.

**Comment by abanet** [comment]
This is working for me with no params:
```
cloudinary?.createUploader().upload(url: URL(fileURLWithPath: path), uploadPreset: "", params: nil, progress:{ progress in
            print("video in progress")
        }) { (response, error) in
            // Handle response
            print(error)
        }
```
Of course in the viewDidLoad I set up my cloudinary conection:
```
    let config = CLDConfiguration(cloudName: "...", apiKey: "...", apiSecret: "..")
    cloudinary = CLDCloudinary(configuration: config)
```

**Comment by nadavofi** [comment]
The following should work for you:

```
let params = CLDUploadRequestParams()
params.setResourceType(CLDUrlResourceType.video)
....
..
```

Resource type can be set either to Image, Video or Raw.

**Comment by ilia-dev** [comment]
@abanet

**Comment by ilia-dev** [comment]
@nadavofi

**Comment by nadavofi** [comment]
I'm marking this as "solved" for the time being. I anyone encounter any additional issues on this matter, please feel free to reopen or submit a new issue. Cheers.

**Comment by bite-me** [comment]
@nadavofi , Thanks .
