### ISSUE TITLE
-995 when using from a share extension

### ISSUE THREAD

**Issue by tapz** [cloudinary/cloudinary_ios#69]
Cloudinary does not set the NSUrlsessionConfiguration.sharedContainerIdentifier, which causes that the connection failes with -995 when made from a share extension. Please provide a way to set the sharedContainerIdentifier.

> Important
> 
> If you attempt to use create a URL session from your app extension but fail to set this property to a valid value, the URL session is invalidated upon creation.

https://developer.apple.com/reference/foundation/nsurlsessionconfiguration/1409450-sharedcontaineridentifier

**Comment by 0xc00010ff** [comment]
@tapz Was there a resolution to this? The decision to adopt Cloudinary into my company's production app is hinging on this.

**Comment by 0xc00010ff** [comment]
```
        let config = CLDConfiguration(cloudName: CLOUDINARY_CLOUD_NAME, apiKey: CLOUDINARY_PUBLIC_KEY, apiSecret: nil)
        let backgroundSessionConfiguration = URLSessionConfiguration.background(withIdentifier: "background.com.myapp.foo")
        backgroundSessionConfiguration.sharedContainerIdentifier = DEFAULTS_GROUP_SUITE
        let cloudinary = CLDCloudinary(configuration: config, networkAdapter: nil, sessionConfiguration: backgroundSessionConfiguration)
```

but I'm getting crashes in Alamofire (inside of Cloudinary) now so.. alright :/

**Comment by roeeba** [comment]
Hi @0xc00010ff. I apologise for the late reply. Not sure if this is still relevant, but this may be caused by not using https - The 'secure' parameter should be set to `true` explicitly:

`let config = CLDConfiguration(cloudName: CLOUDINARY_CLOUD_NAME, apiKey: CLOUDINARY_PUBLIC_KEY, apiSecret: nil, secure: true)`

**Comment by fastma** [comment]
I got this issue, anyone have solution?

**Comment by bbreier** [comment]
I'm having this issue as well

**Comment by bbreier** [comment]
@fastma @0xc00010ff I found that using a snippet like what 0xc00010ff offered, but substituting `URLSessionConfiguration.background(withIdentifier: "background.com.myapp.foo")` with `URLSessionConfiguration.default` solved the problem for me.

**Comment by fastma** [comment]
Can you share your snippet code with share extension @bbreier . I made an changing like your comment but still no luck...

**Comment by bbreier** [comment]
Sure @fastma , sorry for the delayed response!

`lazy var client: CLDCloudinary = {
        let config = CLDConfiguration(cloudName: "name", apiKey: "key", apiSecret: "secret")
        let sessionConfiguration = URLSessionConfiguration.default
        sessionConfiguration.sharedContainerIdentifier = "group.com.appname.sharingextension"
        let cloud = CLDCloudinary(configuration: config, sessionConfiguration: backgroundSessionConfiguration)
        return cloud
}()`

**Comment by fastma** [comment]
Thank you @bbreier , I still got error : 
"Optional(Error Domain=NSURLErrorDomain Code=-999 \"cancelled\" UserInfo={NSErrorFailingURLStringKey=https://api.cloudinary.com/v1_1/owna/image/upload, NSLocalizedDescription=cancelled, NSErrorFailingURLKey=https://api.cloudinary.com/v1_1/owna/image/upload})"

Not sure why... Let me try to investigate more...!

**Comment by Dranix** [comment]
@bbreier Thank you, this solve my issue with -999 error code
