### ISSUE TITLE
New SDK is not allowing to build project.

### ISSUE THREAD

**Issue by tuhinsbuddy** [cloudinary/cloudinary_ios#70]
Updated to the latest SDK and trying to build or achieve the project on Xcode 8.2.1/ Swift 3.0 but it is not able to build or compile. Stuck in "Compiling Swift Files". By downgrading the cloudinary SDK version to  1.0.15 works fine.

**Comment by nadavofi** [comment]
Xcode 8.2.1/ Swift 3.0.2 combination works well on our side. Are you trying this on a fresh new project? Do you see any other errors?

**Comment by tuhinsbuddy** [comment]
First of all it is not a fresh project. This existing project was using cloudinary from the beginning using cocoapods. Updated using cocoapods and it is not allowing to build the entire project. One last thing is that I am not seeing any error on Xcode. Just got stuck while building.

**Comment by nadavofi** [comment]
Please try the following:

- Do you see any errors when running: `pod install --verbose` ?
- Could you try to build a clean project with **cloudinary_ios v2.0.1**? This might help isolating the problem.
- There are many tips and step-by-step instructions out there for clearing all previously installed pods and re-installing it from scratch. This may be helpful as well.

Finally, if neither of these works, please share your podfile so we can try to dig deeper.

**Comment by tuhinsbuddy** [comment]
1. No `pod install --verbose` is not showing any error on my console.
2. I did remove all pods from the project using `pod deintegrate` and `pod clean`. After that reinstall all the pods using `pod install`. Even tried to recreate the entire podfile but nothing helps. FYI the older version is working fine.

**Comment by roeeba** [comment]
Hi, @tuhinsbuddy. I truly apologise for the very delayed reply. We assume that your environment is upgraded now, could you please let us know if it's still relevant?

**Comment by tuhinsbuddy** [comment]
Hello, @roeeba. Thanks for your prompt reply and no problem at all. Yeah! now I am using the latest SDK and this problem has been resolved. Closing this issue for now.
