### ISSUE TITLE
Xcode 8.3 iOS 10.2.1 Uploading gets stuck

### ISSUE THREAD

**Issue by Hemant101** [cloudinary/cloudinary_ios#74]
Hi,

I am using this great class in my app to upload images and get URL.
Issue is that when i have tried to upload with xcode 8.3  and in 10.2.1 iOS  app get stuck and not get image URL.

**Comment by roeeba** [comment]
Hi, @Hemant101. I apologise for the very late reply. Since you opened this issue both Xcode and our SDK were updated. If you still have any issues, please let us know and we'll gladly help.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
