### ISSUE TITLE
Can't Integrate Cloudinary using cocopods.

### ISSUE THREAD

**Issue by subinsuresh991** [cloudinary/cloudinary_ios#75]
target 'Cloudinary_iOS' do
  pod  'Cloudinary', '~> 2.0'
end

while running pod install I m getting error like : 

Analyzing dependencies
Downloading dependencies
Installing Alamofire (4.4.0)
Installing Cloudinary (2.0.1)
**_[!] /bin/bash -c 
set -e
swift ./CLDCrypto/GenerateCLDCryptoModule.swift iphonesimulator .
swift ./CLDCrypto/GenerateCLDCryptoModule.swift iphoneos .

ERROR: ERROR: Failed to determine SDK version for iphonesimulator
xcrun: error: SDK "iphonesimulator" cannot be located
xcrun: error: SDK "iphonesimulator" cannot be located
xcrun: error: unable to lookup item 'SDKVersion' in SDK 'iphonesimulator'

How can I solve this issue?

**Comment by varunvarman** [comment]
Are you using multiple versions of Xcode, on your system?

If so,
then the issue might be related to the presence of these multiple Xcode versions, that the Command line Tool(s) cannot differentiate, during _"pod install"_.
You may have to specify the Xcode version to use during the _"pod install"_, you can do so, by doing the following.

FIX: 

run the command:
`xcode-select --print-path`, from terminal

this command should give you an output like so,
"/Applications/Xcode.app"

this is the path which the _"xcrun"_ and _"xcodebuild"_ refer to, when they are used by/as part of "Command Line Tools", during the _"pod Install"_ command execution to integrate pods into your project(s).

this path should point to the location where your 'Xcode.app' is present (generally its the Application folder, thus the path comes/forms to "/Applications/Xcode.app"), if it does not do so, this causes the Command Line Tool(s), to be unable, to refer to that Xcode version to fetch build information.

You can specify the path by running, from terminal,
`$sudo xcode-select --switch path_to_where_xcode_is_present`
_Example: "$sudo xcode-select --switch /Applications/Xcode.app"_
Note: Don't forget _"$sudo"_

this will cause the path to be set which ultimately can be used by the Command Line Tools to fetch the relevant information from the desired Xcode version, whenever you run _"pod install"_ again.

you can confirm, the set path, by again running, `xcode-select --print-path`, from terminal, to check if the path is set to what you wish.

hope this helps,
regards.

**Comment by vishaluae** [comment]
@varunvarman This worked. I had Xcode 7.3 and Xcode 8 installed in my system.

The path was pointing to v7.3 instead of the latest Xcode. Changed the path to the latest version and was able to pod install Cloudinary.

Thanks!

**Comment by manikad24** [comment]
@subinsuresh991 Thanks. worked for me.

**Comment by roeeba** [comment]
Hey, guys. It looks like you managed to resolve this issue. I'm safely closing this thread now but feel free to re-open it or open a new thread if you still need help.

**Comment by harshadmadaye** [comment]
> @subinsuresh991
> 
> Are you using multiple versions of Xcode, on your system?
> 
> If so,
> then the issue might be related to the presence of these multiple Xcode versions, that the Command line Tool(s) cannot differentiate, during _"pod install"_.
> You may have to specify the Xcode version to use during the _"pod install"_, you can do so, by doing the following.
> 
> FIX:
> 
> run the command:
> `xcode-select --print-path`, from terminal
> 
> this command should give you an output like so,
> "/Applications/Xcode.app"
> 
> this is the path which the _"xcrun"_ and _"xcodebuild"_ refer to, when they are used by/as part of "Command Line Tools", during the _"pod Install"_ command execution to integrate pods into your project(s).
> 
> this path should point to the location where your 'Xcode.app' is present (generally its the Application folder, thus the path comes/forms to "/Applications/Xcode.app"), if it does not do so, this causes the Command Line Tool(s), to be unable, to refer to that Xcode version to fetch build information.
> 
> You can specify the path by running, from terminal,
> `$sudo xcode-select --switch path_to_where_xcode_is_present`
> _Example: "$sudo xcode-select --switch /Applications/Xcode.app"_
> Note: Don't forget _"$sudo"_
> 
> this will cause the path to be set which ultimately can be used by the Command Line Tools to fetch the relevant information from the desired Xcode version, whenever you run _"pod install"_ again.
> 
> you can confirm, the set path, by again running, `xcode-select --print-path`, from terminal, to check if the path is set to what you wish.
> 
> hope this helps,
> regards.

i had only one xcode in my new mac, but this solution still worked for me, thanks

**Comment by harshadmadaye** [comment]
@subinsuresh991  i had only one xcode in my new mac, but this solution still worked for me, thanks
