### ISSUE TITLE
Tried to upload image it is given error "Stale request - reported time"

### ISSUE THREAD

**Issue by hitenpethani** [cloudinary/cloudinary_ios#76]
I tried to upload images from Cloudinary sever but it returns error  "Stale request - reported time". i am using iOS 10.2.1 devices and xcode 8.3 tools. i have attached error screenshot please see attachment.

![screen shot 2017-02-28 at 1 39 08 pm](https://cloud.githubusercontent.com/assets/26093838/23482105/dfcfe7fe-fe9b-11e6-8b81-6cdd2b028ea0.png)

**Comment by roeeba** [comment]
Hi @hitenpethani, last week Cloudinary had some issues with uploading new images  - https://status.cloudinary.com/incidents/n1b1868fk0d6, which might be related. 
Can you please let us know if you still face this issue?

**Comment by hitenpethani** [comment]
Nope, My issue is solve.

**Comment by roeeba** [comment]
Stale requests are caused when the timestamp in the signature sent for signed uploads is too old. It could probably mean that there was something wrong with your architecture.
