### ISSUE TITLE
Downloading resources

### ISSUE THREAD

**Issue by tspent** [cloudinary/cloudinary_ios#78]
Is there any way to know from the publicID the type of the resource? Image or video?

**Comment by MaorGariv** [comment]
Hi,

The resource's `publicID` is not related to a specific `resourceType`. It means that you can have the option to name a video and an image with the same`publicID`.

**Comment by MaorGariv** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
