### ISSUE TITLE
Misleading information in README.md about minimum iOS version

### ISSUE THREAD

**Issue by dkarbayev** [cloudinary/cloudinary_ios#79]
`README.md` states that this pod requires iOS 8.0+ while in `Cloudinary.podspec` the minimum version is higher: `s.ios.deployment_target = '9.0'`.
Is it possible to downgrade required deployment target to 8.0 (in order to cover as much devices as possible)?

**Comment by roeeba** [comment]
For reference - This was already fixed. podspec now points to 8.0.
