### ISSUE TITLE
Cloudinary custom category class for NSDictionary crashes app

### ISSUE THREAD

**Issue by mikewli** [cloudinary/cloudinary_ios#8]
The bug crashes any app that tries to use the upload functionality for iOS (and the signature option is nil), since there is a problem with the way the framework includes the category class overriding Apple's **NSDictionary** class.

The bug occurs at **CLUploader.m** in line 552, since the category you define for NSDictionary isn't overridden with a category **unless** the implementation is also included in the file.  So the fix I propose is to include **NSDictionary+CLUtilities.m** instead of **NSDictionary+CLUtilities.h** so that **NSDictionary** is properly overridden and has the method.  I've successfully changed my own downloaded copy of it to fix this issue, but I'm leaving the change up to you guys, the developers.

EDIT: An alternate solution would be to have the NSDictionary utilities class imported like how UIImageView or other extended classes via categories is imported via AFNetworking (you have to include the AFNetworking in the build settings as well as importing the .h of the category class, so this approach isn't "transparent" to the user without a walkthrough, however.

**Comment by danielwmsun** [comment]
@mikewli How do I fix this if I've included the project manually? I only have the header files in my project and the ".a" files in my frameworks folder.

**Comment by mikewli** [comment]
I've moved on from using this library and it's been over 2 years since I have, so I'm not sure how I can help you. Sorry about not closing it earlier.
