### ISSUE TITLE
Can't Build CLDCryptoUtils.swift Error!

### ISSUE THREAD

**Issue by JosephNK** [cloudinary/cloudinary_ios#80]
I updated Xcode today. [ Xcode Current Version: 8.3 (8E162) ] [ Support: iOS 10.3 ]
It does not become a build. :sob:

![2017-03-283 24 30](https://cloud.githubusercontent.com/assets/1622085/24391582/ec48ec76-13ca-11e7-9e8c-1ee33b1897a4.png)

**Comment by JosephNK** [comment]
First of all, I solved it temporarily.

![2017-03-284 54 41](https://cloud.githubusercontent.com/assets/1622085/24394575/74cb9e16-13d7-11e7-8c44-2e3a988ffafa.png)

**Comment by IrinaErnst** [comment]
I have the same issue. Where can I find "module.map"?

**Comment by JosephNK** [comment]
@IrinaErnst 
/<Your Project Path>/Pods/Cloudinary/Cloudinary/Frameworks/CLDCrypto/iphoneos/CLDCrypto.framework/module.map
/<Your Project Path>/Pods/Cloudinary/Cloudinary/Frameworks/CLDCrypto/iphonesimulator/CLDCrypto.framework/module.map

**Comment by ouss-athome** [comment]
Any update on a way to definitively fix this issue please?

**Comment by nadavofi** [comment]
Thank you for pointing this out.
We're looking into resolving this thoroughly on the SDK. Meantime, please try to run the following command (from `cloudinary.pbxproj`):

    xcrun -sdk macosx swift ./CLDCrypto/GenerateCLDCryptoModule.swift $PLATFORM_NAME $PROJECT_DIR

Let me know if this solves the build issues for you.

**Comment by astachelek** [comment]
I ran into this issue with Cloudinary iOS v2.0.2 and Xcode 9 again. Manually running the xcrun command above let's me hand-repair this situation, but it would be nice of there was a way to not have to reinstall the CLDCrypto library every time we update this Cocoapods. 

Any ideas on this?

**Comment by roeeba** [comment]
Hi, @ashachak. Please see our answer on #107. For the time being, this is the quickest solution. We're looking into a more feasible solution.
