### ISSUE TITLE
Module compiled with Swift 3.0.2 cannot be imported in Swift 3.1

### ISSUE THREAD

**Issue by Nautiyalsachin** [cloudinary/cloudinary_ios#81]
I just downloaded the new xcode 8.3 and now I am getting the error of "Module compiled with Swift 3.0.2 cannot be imported in Swift 3.1" please look into this.

**Comment by tspent** [comment]
change the module path from /Applications/Xcode/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk to /Applications/Xcode/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk

**Comment by MaorGariv** [comment]
Hi @Nautiyalsachin,

Sorry for the delayed response on this issue.

Did @tspent suggestion help?

Let me know of any updates.

**Comment by Nautiyalsachin** [comment]
Yes it did thank you.
