### ISSUE TITLE
Apple Mach-O Linker Warning

### ISSUE THREAD

**Issue by 0xc00010ff** [cloudinary/cloudinary_ios#82]
Not a big deal but...

![screen shot 2017-04-06 at 11 42 18 pm](https://cloud.githubusercontent.com/assets/4950729/24788509/cac98ede-1b22-11e7-8fcb-04bdfe26f6cb.png)

Shows as a warning in the Pod framework, and each target of my app. 
The library seems to be running alright for uploading (minus Issue https://github.com/cloudinary/cloudinary_ios/issues/77), but its the only warning in my app so its kind of an eye sore :/

**Comment by JosephNK** [comment]
me, too...  I want to remove the warning.
Please solve it!

**Comment by jxtmo** [comment]
why isn't this solved yet!

**Comment by tocker** [comment]
This should be solved in version 2.0.2.
Please run 

```
pod repo update
pod install
```

to update the Cloudinary pod to 2.0.2 and rebuild.
