### ISSUE TITLE
Unable to add SDK as a submodule - username and password required

### ISSUE THREAD

**Issue by laideybug** [cloudinary/cloudinary_ios#84]
I use Carthage as my dependency manager so I have to add the SDK to my project manually. However, when running the command `git submodule add http://git.zemingo.com/Cloudinary/CloudinarySDK-iOS.git`, I am prompted for a username and password. My Cloudinary account credentials do not work for this.

What credentials am I supposed to use in order to gain access to the project?

**Comment by roeeba** [comment]
Hi @laideybug, I apologise for the delayed reply. Please use `git submodule add https://github.com/cloudinary/cloudinary_ios.git` instead of `http://git.zemingo.com/Cloudinary/CloudinarySDK-iOS.git`. We have updated the documentation accordingly.
