### ISSUE TITLE
Uploading over 100mb

### ISSUE THREAD

**Issue by rymanalo** [cloudinary/cloudinary_ios#89]
http://cloudinary.com/documentation/upload_videos#chunked_video_upload

The above mentions using an upload_large function. Does the SDK support this? What parameters should be set to upload files greater than 100mb?

**Comment by idobarnoam** [comment]
Hi

Our iOS library is still missing the implementation of chunk-upload. It's on our roadmap, however, I don't currently have an ETA for its arrival.
I'll be happy to update you once it becomes available though.

If this is urgent then you may want to go ahead and implement it yourself.
The following article may give you a sense of what chunked upload means and can also be useful in-case you decide to implement it on your own:
https://support.cloudinary.com/hc/en-us/articles/208263735-Guidelines-for-self-implementing-chunked-upload-to-Cloudinary

Note that all of our SDKs are completely open-source and we encourage the Cloudinary community to join in the effort of improving and enhancing its capabilities.

**Comment by idobarnoam** [comment]
@rymanalo I'm currently closing this issue as there is no change in the request. Once this would be implemented we would let you know and update the thread.

**Comment by idobarnoam** [comment]
Hi @rymanalo Just wanted to update that we updated the SDK to support chunked uploads.
Let us know if you have any further questions.

**Comment by rymanalo** [comment]
@idobarnoam Yes, I am able to use the new uploadLarge feature. What is weird now is that the files I'm uploading are not being added to the folder I specified in an upload preset I created. I've worked around that problem though.

**Comment by roeeba** [comment]
Hi @rymanalo. In order to better understand the issue, can you please share more details (your cloud_name, upload_preset, the code you used)? how did you work around it? thanks!

**Comment by rymanalo** [comment]
@roeeba I created an upload_preset in the Upload Settings. I designated a folder name in the following box:
<img width="586" alt="screen shot 2017-12-02 at 3 46 42 pm" src="https://user-images.githubusercontent.com/2898384/33520909-b61529c2-d778-11e7-81d9-a01a292e7c00.png">
Everything worked fine.

After changing to the uploadLarge, I noticed that video files over 5 seconds long would not have the folder as part of the PublicId (I was testing with durations of 5, 10, 15, and 25). I edited the above box with a different folder name. The folder name would always show up for files under 5 seconds. I decided to remove the folder name and attach it to the PublicId in code. That worked out fine.

`let params = CLDUploadRequestParams()
let folderName = "folderName/"
let filename = "filename"
params.setPublicId("\(folderName)\(filename)")`

**Comment by roeeba** [comment]
Hi @rymanalo. Thank you for for the detailed response! We'll try to reproduce it on our side. Update to follow.

**Comment by roeeba** [comment]
Hi @rymanalo. We don't manage to reproduce the issue you're describing. Could you please share your cloud name so we can check your logs? if you rather keep it private please feel free to open a support ticket. Thanks

**Comment by idobarnoam** [comment]
Hi
As it is probably not relevant anymore, we’re closing this issue.

Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket, if our assistance is still needed.
